cmd_/home/akshayk/GranaryCode/Granary-Drk/src/core/kernel_linux/modules/../../kernel_linux/simple_tests/exception_asm.o := gcc -Wp,-MD,/home/akshayk/GranaryCode/Granary-Drk/src/core/kernel_linux/modules/../../kernel_linux/simple_tests/.exception_asm.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/4.7/include -I/home/akshayk/GranaryCode/Granary-Drk/src/debugging/linux-3.2.33/arch/x86/include -Iarch/x86/include/generated -Iinclude  -include /home/akshayk/GranaryCode/Granary-Drk/src/debugging/linux-3.2.33/include/linux/kconfig.h -D__KERNEL__ -D__ASSEMBLY__ -m64 -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1  -gdwarf-2    -DDR_REG_ENUM_COMPATIBILITY -DX86_64 -DLINUX -DLINUX_KERNEL -I/home/akshayk/GranaryCode/Granary-Drk/src/core/lib/include -I/home/akshayk/GranaryCode/Granary-Drk/src/core/kernel_linux -I/home/akshayk/GranaryCode/Granary-Drk/src/core/lib -I/home/akshayk/GranaryCode/Granary-Drk/src/core/x86 -I/home/akshayk/GranaryCode/Granary-Drk/src/core -Xassembler -mmnemonic=intel -Xassembler -msyntax=intel -Xassembler -mnaked-reg -Xassembler --noexecstack -Xassembler --64  -DMODULE  -c -o /home/akshayk/GranaryCode/Granary-Drk/src/core/kernel_linux/modules/../../kernel_linux/simple_tests/exception_asm.o /home/akshayk/GranaryCode/Granary-Drk/src/core/kernel_linux/modules/../../kernel_linux/simple_tests/exception_asm.S

source_/home/akshayk/GranaryCode/Granary-Drk/src/core/kernel_linux/modules/../../kernel_linux/simple_tests/exception_asm.o := /home/akshayk/GranaryCode/Granary-Drk/src/core/kernel_linux/modules/../../kernel_linux/simple_tests/exception_asm.S

deps_/home/akshayk/GranaryCode/Granary-Drk/src/core/kernel_linux/modules/../../kernel_linux/simple_tests/exception_asm.o := \

/home/akshayk/GranaryCode/Granary-Drk/src/core/kernel_linux/modules/../../kernel_linux/simple_tests/exception_asm.o: $(deps_/home/akshayk/GranaryCode/Granary-Drk/src/core/kernel_linux/modules/../../kernel_linux/simple_tests/exception_asm.o)

$(deps_/home/akshayk/GranaryCode/Granary-Drk/src/core/kernel_linux/modules/../../kernel_linux/simple_tests/exception_asm.o):
