
BEGIN_MOP

    DEF_TYPE(struct list_head)
        DEF_FIELD(struct list_head,next,1,1)
        DEF_FIELD(struct list_head,prev,2,0)
    END_TYPE

    DEF_TYPE(atomic_t)
        DEF_FIELD(atomic_t,counter,16,1)
    END_TYPE

    DEF_TYPE(atomic64_t)
        DEF_FIELD(atomic64_t,counter,17,1)
    END_TYPE

    DEF_TYPE(struct raw_spinlock)
        DEF_FIELD(struct raw_spinlock,slock,18,1)
    END_TYPE

    DEF_TYPE(spinlock_t)
        DEF_FIELD(spinlock_t,raw_lock,19,1)
    END_TYPE

    DEF_TYPE(struct netdev_hw_addr_list)
        DEF_FIELD(struct netdev_hw_addr_list,list,20,1)
        DEF_FIELD(struct netdev_hw_addr_list,count,21,0)
    END_TYPE

    DEF_TYPE(struct net_device_stats)
        DEF_FIELD(struct net_device_stats,rx_packets,22,1)
        DEF_FIELD(struct net_device_stats,tx_packets,23,0)
        DEF_FIELD(struct net_device_stats,rx_bytes,24,0)
        DEF_FIELD(struct net_device_stats,tx_bytes,25,0)
        DEF_FIELD(struct net_device_stats,rx_errors,26,0)
        DEF_FIELD(struct net_device_stats,tx_errors,27,0)
        DEF_FIELD(struct net_device_stats,rx_dropped,28,0)
        DEF_FIELD(struct net_device_stats,tx_dropped,29,0)
        DEF_FIELD(struct net_device_stats,multicast,30,0)
        DEF_FIELD(struct net_device_stats,collisions,31,0)
        DEF_FIELD(struct net_device_stats,rx_length_errors,32,0)
        DEF_FIELD(struct net_device_stats,rx_over_errors,33,0)
        DEF_FIELD(struct net_device_stats,rx_crc_errors,34,0)
        DEF_FIELD(struct net_device_stats,rx_frame_errors,35,0)
        DEF_FIELD(struct net_device_stats,rx_fifo_errors,36,0)
        DEF_FIELD(struct net_device_stats,rx_missed_errors,37,0)
        DEF_FIELD(struct net_device_stats,tx_aborted_errors,38,0)
        DEF_FIELD(struct net_device_stats,tx_carrier_errors,39,0)
        DEF_FIELD(struct net_device_stats,tx_fifo_errors,40,0)
        DEF_FIELD(struct net_device_stats,tx_heartbeat_errors,41,0)
        DEF_FIELD(struct net_device_stats,tx_window_errors,42,0)
        DEF_FIELD(struct net_device_stats,rx_compressed,43,0)
        DEF_FIELD(struct net_device_stats,tx_compressed,44,0)
    END_TYPE

    DEF_TYPE(struct pm_message)
        DEF_FIELD(struct pm_message,event,45,1)
    END_TYPE

    DEF_TYPE(struct hlist_node)
        DEF_FIELD(struct hlist_node,next,46,1)
        DEF_FIELD(struct hlist_node,pprev,47,0)
    END_TYPE

    DEF_TYPE(struct firmware)
        DEF_FIELD(struct firmware,size,49,1)
        DEF_FIELD(struct firmware,data,50,0)
        DEF_FIELD(struct firmware,pages,51,0)
    END_TYPE

    DEF_TYPE(struct semaphore)
        DEF_FIELD(struct semaphore,lock,52,1)
        DEF_FIELD(struct semaphore,count,53,0)
        DEF_FIELD(struct semaphore,wait_list,54,0)
    END_TYPE

    DEF_TYPE(struct kref)
        DEF_FIELD(struct kref,refcount,56,1)
    END_TYPE

    DEF_TYPE(struct __wait_queue_head)
        DEF_FIELD(struct __wait_queue_head,lock,59,1)
        DEF_FIELD(struct __wait_queue_head,task_list,60,0)
    END_TYPE

    DEF_TYPE(struct timer_list)
        DEF_FIELD(struct timer_list,entry,62,1)
        DEF_FIELD(struct timer_list,expires,63,0)
        DEF_FIELD(struct timer_list,function,64,0)
        DEF_FIELD(struct timer_list,data,65,0)
        DEF_FIELD(struct timer_list,base,66,0)
        DEF_FIELD(struct timer_list,start_site,67,0)
        DEF_FIELD(struct timer_list,start_comm,68,0)
        DEF_FIELD(struct timer_list,start_pid,69,0)
    END_TYPE

    DEF_TYPE(struct pci_dynids)
        DEF_FIELD(struct pci_dynids,lock,70,1)
        DEF_FIELD(struct pci_dynids,list,71,0)
    END_TYPE

    DEF_TYPE(struct work_struct)
        DEF_FIELD(struct work_struct,data,75,1)
        DEF_FIELD(struct work_struct,entry,76,0)
        DEF_FIELD(struct work_struct,func,77,0)
    END_TYPE

    DEF_TYPE(struct dev_pm_info)
        DEF_FIELD(struct dev_pm_info,power_state,78,1)
        DEF_FIELD(struct dev_pm_info,can_wakeup,79,0)
        DEF_FIELD(struct dev_pm_info,should_wakeup,80,0)
        DEF_FIELD(struct dev_pm_info,status,81,0)
        DEF_FIELD(struct dev_pm_info,entry,82,0)
        DEF_FIELD(struct dev_pm_info,suspend_timer,83,0)
        DEF_FIELD(struct dev_pm_info,timer_expires,84,0)
        DEF_FIELD(struct dev_pm_info,work,85,0)
        DEF_FIELD(struct dev_pm_info,wait_queue,86,0)
        DEF_FIELD(struct dev_pm_info,lock,87,0)
        DEF_FIELD(struct dev_pm_info,usage_count,88,0)
        DEF_FIELD(struct dev_pm_info,child_count,89,0)
        DEF_FIELD(struct dev_pm_info,disable_depth,90,0)
        DEF_FIELD(struct dev_pm_info,ignore_children,91,0)
        DEF_FIELD(struct dev_pm_info,idle_notification,92,0)
        DEF_FIELD(struct dev_pm_info,request_pending,93,0)
        DEF_FIELD(struct dev_pm_info,deferred_resume,94,0)
        DEF_FIELD(struct dev_pm_info,request,95,0)
        DEF_FIELD(struct dev_pm_info,runtime_status,96,0)
        DEF_FIELD(struct dev_pm_info,runtime_error,97,0)
    END_TYPE

    DEF_TYPE(struct kobject)
        DEF_FIELD(struct kobject,name,98,1)
        DEF_FIELD(struct kobject,entry,99,0)
        DEF_FIELD(struct kobject,parent,100,0)
        DEF_FIELD(struct kobject,kset,101,0)
        DEF_FIELD(struct kobject,ktype,102,0)
        DEF_FIELD(struct kobject,sd,103,0)
        DEF_FIELD(struct kobject,kref,104,0)
        DEF_FIELD(struct kobject,state_initialized,105,0)
        DEF_FIELD(struct kobject,state_in_sysfs,106,0)
        DEF_FIELD(struct kobject,state_add_uevent_sent,107,0)
        DEF_FIELD(struct kobject,state_remove_uevent_sent,108,0)
        DEF_FIELD(struct kobject,uevent_suppress,109,0)
    END_TYPE

    DEF_TYPE(struct dev_archdata)
        DEF_FIELD(struct dev_archdata,acpi_handle,110,1)
        DEF_FIELD(struct dev_archdata,dma_ops,111,0)
    END_TYPE

    DEF_TYPE(struct klist_node)
        DEF_FIELD(struct klist_node,n_klist,114,1)
        DEF_FIELD(struct klist_node,n_node,115,0)
        DEF_FIELD(struct klist_node,n_ref,116,0)
    END_TYPE

    DEF_TYPE(struct device)
        DEF_FIELD(struct device,parent,118,1)
        DEF_FIELD(struct device,p,119,0)
        DEF_FIELD(struct device,kobj,120,0)
        DEF_FIELD(struct device,init_name,121,0)
        DEF_FIELD(struct device,type,122,0)
        DEF_FIELD(struct device,sem,123,0)
        DEF_FIELD(struct device,bus,124,0)
        DEF_FIELD(struct device,driver,125,0)
        DEF_FIELD(struct device,platform_data,126,0)
        DEF_FIELD(struct device,power,127,0)
        DEF_FIELD(struct device,numa_node,128,0)
        DEF_FIELD(struct device,dma_mask,129,0)
        DEF_FIELD(struct device,coherent_dma_mask,130,0)
        DEF_FIELD(struct device,dma_parms,131,0)
        DEF_FIELD(struct device,dma_pools,132,0)
        DEF_FIELD(struct device,dma_mem,133,0)
        DEF_FIELD(struct device,archdata,134,0)
        DEF_FIELD(struct device,devt,135,0)
        DEF_FIELD(struct device,devres_lock,136,0)
        DEF_FIELD(struct device,devres_head,137,0)
        DEF_FIELD(struct device,knode_class,138,0)
        DEF_FIELD(struct device,class1,139,0)
        DEF_FIELD(struct device,groups,140,0)
        DEF_FIELD(struct device,release,141,0)
    END_TYPE

    DEF_TYPE(struct netdev_queue)
        DEF_FIELD(struct netdev_queue,dev,142,1)
        DEF_FIELD(struct netdev_queue,qdisc,143,0)
        DEF_FIELD(struct netdev_queue,state,144,0)
        DEF_FIELD(struct netdev_queue,qdisc_sleeping,145,0)
        DEF_FIELD(struct netdev_queue,_xmit_lock,146,0)
        DEF_FIELD(struct netdev_queue,xmit_lock_owner,147,0)
        DEF_FIELD(struct netdev_queue,trans_start,148,0)
        DEF_FIELD(struct netdev_queue,tx_bytes,149,0)
        DEF_FIELD(struct netdev_queue,tx_packets,150,0)
        DEF_FIELD(struct netdev_queue,tx_dropped,151,0)
    END_TYPE

    DEF_TYPE(union ktime)
        DEF_FIELD(union ktime,tv64,154,1)
    END_TYPE

    DEF_TYPE(struct sk_buff)
        DEF_FIELD(struct sk_buff,next,160,1)
        DEF_FIELD(struct sk_buff,prev,161,0)
        DEF_FIELD(struct sk_buff,sk,162,0)
        DEF_FIELD(struct sk_buff,tstamp,163,0)
        DEF_FIELD(struct sk_buff,dev,164,0)
        DEF_FIELD(struct sk_buff,_skb_dst,165,0)
        DEF_FIELD(struct sk_buff,cb,166,0)
        DEF_FIELD(struct sk_buff,len,167,0)
        DEF_FIELD(struct sk_buff,data_len,168,0)
        DEF_FIELD(struct sk_buff,mac_len,169,0)
        DEF_FIELD(struct sk_buff,hdr_len,170,0)
        DEF_FIELD(struct sk_buff,csum,171,0)
        DEF_FIELD(struct sk_buff,csum_start,172,0)
        DEF_FIELD(struct sk_buff,csum_offset,173,0)
        DEF_FIELD(struct sk_buff,priority,174,0)
        DEF_FIELD(struct sk_buff,flags1_begin,175,0)
        DEF_FIELD(struct sk_buff,local_df,176,0)
        DEF_FIELD(struct sk_buff,cloned,177,0)
        DEF_FIELD(struct sk_buff,ip_summed,178,0)
        DEF_FIELD(struct sk_buff,nohdr,179,0)
        DEF_FIELD(struct sk_buff,nfctinfo,180,0)
        DEF_FIELD(struct sk_buff,pkt_type,181,0)
        DEF_FIELD(struct sk_buff,fclone,182,0)
        DEF_FIELD(struct sk_buff,ipvs_property,183,0)
        DEF_FIELD(struct sk_buff,peeked,184,0)
        DEF_FIELD(struct sk_buff,nf_trace,185,0)
        DEF_FIELD(struct sk_buff,protocol,186,0)
        DEF_FIELD(struct sk_buff,flags1_end,187,0)
        DEF_FIELD(struct sk_buff,destructor,188,0)
        DEF_FIELD(struct sk_buff,iif,189,0)
        DEF_FIELD(struct sk_buff,tc_index,190,0)
        DEF_FIELD(struct sk_buff,tc_verd,191,0)
        DEF_FIELD(struct sk_buff,flags2_begin,192,0)
        DEF_FIELD(struct sk_buff,queue_mapping,193,0)
        DEF_FIELD(struct sk_buff,flags2_end,194,0)
        DEF_FIELD(struct sk_buff,secmark,195,0)
        DEF_FIELD(struct sk_buff,mark,196,0)
        DEF_FIELD(struct sk_buff,vlan_tci,197,0)
        DEF_FIELD(struct sk_buff,transport_header,198,0)
        DEF_FIELD(struct sk_buff,network_header,199,0)
        DEF_FIELD(struct sk_buff,mac_header,200,0)
        DEF_FIELD(struct sk_buff,tail,201,0)
        DEF_FIELD(struct sk_buff,end,202,0)
        DEF_FIELD(struct sk_buff,head,203,0)
        DEF_FIELD(struct sk_buff,data,204,0)
        DEF_FIELD(struct sk_buff,truesize,205,0)
        DEF_FIELD(struct sk_buff,users,206,0)
    END_TYPE

    DEF_TYPE(struct net_device_ops)
        DEF_FIELD(struct net_device_ops,ndo_init,207,1)
        DEF_FIELD(struct net_device_ops,ndo_uninit,208,0)
        DEF_FIELD(struct net_device_ops,ndo_open,209,0)
        DEF_FIELD(struct net_device_ops,ndo_stop,210,0)
        DEF_FIELD(struct net_device_ops,ndo_start_xmit,211,0)
        DEF_FIELD(struct net_device_ops,ndo_select_queue,212,0)
        DEF_FIELD(struct net_device_ops,ndo_change_rx_flags,213,0)
        DEF_FIELD(struct net_device_ops,ndo_set_rx_mode,214,0)
        DEF_FIELD(struct net_device_ops,ndo_set_multicast_list,215,0)
        DEF_FIELD(struct net_device_ops,ndo_set_mac_address,216,0)
        DEF_FIELD(struct net_device_ops,ndo_validate_addr,217,0)
        DEF_FIELD(struct net_device_ops,ndo_do_ioctl,218,0)
        DEF_FIELD(struct net_device_ops,ndo_set_config,219,0)
        DEF_FIELD(struct net_device_ops,ndo_change_mtu,220,0)
        DEF_FIELD(struct net_device_ops,ndo_neigh_setup,221,0)
        DEF_FIELD(struct net_device_ops,ndo_tx_timeout,222,0)
        DEF_FIELD(struct net_device_ops,ndo_get_stats,223,0)
        DEF_FIELD(struct net_device_ops,ndo_vlan_rx_register,224,0)
        DEF_FIELD(struct net_device_ops,ndo_vlan_rx_add_vid,225,0)
        DEF_FIELD(struct net_device_ops,ndo_vlan_rx_kill_vid,226,0)
        DEF_FIELD(struct net_device_ops,ndo_poll_controller,227,0)
        DEF_FIELD(struct net_device_ops,ndo_fcoe_enable,228,0)
        DEF_FIELD(struct net_device_ops,ndo_fcoe_disable,229,0)
        DEF_FIELD(struct net_device_ops,ndo_fcoe_ddp_setup,230,0)
        DEF_FIELD(struct net_device_ops,ndo_fcoe_ddp_done,231,0)
    END_TYPE

    DEF_TYPE(struct ethtool_ops)
        DEF_FIELD(struct ethtool_ops,get_settings,232,1)
        DEF_FIELD(struct ethtool_ops,set_settings,233,0)
        DEF_FIELD(struct ethtool_ops,get_drvinfo,234,0)
        DEF_FIELD(struct ethtool_ops,get_regs_len,235,0)
        DEF_FIELD(struct ethtool_ops,get_regs,236,0)
        DEF_FIELD(struct ethtool_ops,get_wol,237,0)
        DEF_FIELD(struct ethtool_ops,set_wol,238,0)
        DEF_FIELD(struct ethtool_ops,get_msglevel,239,0)
        DEF_FIELD(struct ethtool_ops,set_msglevel,240,0)
        DEF_FIELD(struct ethtool_ops,nway_reset,241,0)
        DEF_FIELD(struct ethtool_ops,get_link,242,0)
        DEF_FIELD(struct ethtool_ops,get_eeprom_len,243,0)
        DEF_FIELD(struct ethtool_ops,get_eeprom,244,0)
        DEF_FIELD(struct ethtool_ops,set_eeprom,245,0)
        DEF_FIELD(struct ethtool_ops,get_coalesce,246,0)
        DEF_FIELD(struct ethtool_ops,set_coalesce,247,0)
        DEF_FIELD(struct ethtool_ops,get_ringparam,248,0)
        DEF_FIELD(struct ethtool_ops,set_ringparam,249,0)
        DEF_FIELD(struct ethtool_ops,get_pauseparam,250,0)
        DEF_FIELD(struct ethtool_ops,set_pauseparam,251,0)
        DEF_FIELD(struct ethtool_ops,get_rx_csum,252,0)
        DEF_FIELD(struct ethtool_ops,set_rx_csum,253,0)
        DEF_FIELD(struct ethtool_ops,get_tx_csum,254,0)
        DEF_FIELD(struct ethtool_ops,set_tx_csum,255,0)
        DEF_FIELD(struct ethtool_ops,get_sg,256,0)
        DEF_FIELD(struct ethtool_ops,set_sg,257,0)
        DEF_FIELD(struct ethtool_ops,get_tso,258,0)
        DEF_FIELD(struct ethtool_ops,set_tso,259,0)
        DEF_FIELD(struct ethtool_ops,self_test,260,0)
        DEF_FIELD(struct ethtool_ops,get_strings,261,0)
        DEF_FIELD(struct ethtool_ops,phys_id,262,0)
        DEF_FIELD(struct ethtool_ops,get_ethtool_stats,263,0)
        DEF_FIELD(struct ethtool_ops,begin,264,0)
        DEF_FIELD(struct ethtool_ops,complete,265,0)
        DEF_FIELD(struct ethtool_ops,get_ufo,266,0)
        DEF_FIELD(struct ethtool_ops,set_ufo,267,0)
        DEF_FIELD(struct ethtool_ops,get_flags,268,0)
        DEF_FIELD(struct ethtool_ops,set_flags,269,0)
        DEF_FIELD(struct ethtool_ops,get_priv_flags,270,0)
        DEF_FIELD(struct ethtool_ops,set_priv_flags,271,0)
        DEF_FIELD(struct ethtool_ops,get_sset_count,272,0)
        DEF_FIELD(struct ethtool_ops,self_test_count,273,0)
        DEF_FIELD(struct ethtool_ops,get_stats_count,274,0)
        DEF_FIELD(struct ethtool_ops,get_rxnfc,275,0)
        DEF_FIELD(struct ethtool_ops,set_rxnfc,276,0)
        DEF_FIELD(struct ethtool_ops,flash_device,277,0)
        DEF_FIELD(struct ethtool_ops,reset,278,0)
    END_TYPE

    DEF_TYPE(struct net_device)
        DEF_FIELD(struct net_device,name,279,1)
        DEF_FIELD(struct net_device,name_hlist,280,0)
        DEF_FIELD(struct net_device,ifalias,281,0)
        DEF_FIELD(struct net_device,mem_end,282,0)
        DEF_FIELD(struct net_device,mem_start,283,0)
        DEF_FIELD(struct net_device,base_addr,284,0)
        DEF_FIELD(struct net_device,irq,285,0)
        DEF_FIELD(struct net_device,if_port,286,0)
        DEF_FIELD(struct net_device,dma,287,0)
        DEF_FIELD(struct net_device,state,288,0)
        DEF_FIELD(struct net_device,dev_list,289,0)
        DEF_FIELD(struct net_device,napi_list,290,0)
        DEF_FIELD(struct net_device,features,291,0)
        DEF_FIELD(struct net_device,ifindex,292,0)
        DEF_FIELD(struct net_device,iflink,293,0)
        DEF_FIELD(struct net_device,stats,294,0)
        DEF_FIELD(struct net_device,wireless_handlers,295,0)
        DEF_FIELD(struct net_device,wireless_data,296,0)
        DEF_FIELD(struct net_device,netdev_ops,297,0)
        DEF_FIELD(struct net_device,ethtool_ops,298,0)
        DEF_FIELD(struct net_device,header_ops,299,0)
        DEF_FIELD(struct net_device,flags,300,0)
        DEF_FIELD(struct net_device,gflags,301,0)
        DEF_FIELD(struct net_device,priv_flags,302,0)
        DEF_FIELD(struct net_device,padded,303,0)
        DEF_FIELD(struct net_device,operstate,304,0)
        DEF_FIELD(struct net_device,link_mode,305,0)
        DEF_FIELD(struct net_device,mtu,306,0)
        DEF_FIELD(struct net_device,type,307,0)
        DEF_FIELD(struct net_device,hard_header_len,308,0)
        DEF_FIELD(struct net_device,needed_headroom,309,0)
        DEF_FIELD(struct net_device,needed_tailroom,310,0)
        DEF_FIELD(struct net_device,master,311,0)
        DEF_FIELD(struct net_device,perm_addr,312,0)
        DEF_FIELD(struct net_device,addr_len,313,0)
        DEF_FIELD(struct net_device,dev_id,314,0)
        DEF_FIELD(struct net_device,uc,315,0)
        DEF_FIELD(struct net_device,uc_promisc,316,0)
        DEF_FIELD(struct net_device,addr_list_lock,317,0)
        DEF_FIELD(struct net_device,mc_list,318,0)
        DEF_FIELD(struct net_device,mc_count,319,0)
        DEF_FIELD(struct net_device,promiscuity,320,0)
        DEF_FIELD(struct net_device,allmulti,321,0)
        DEF_FIELD(struct net_device,dsa_ptr,322,0)
        DEF_FIELD(struct net_device,atalk_ptr,323,0)
        DEF_FIELD(struct net_device,ip_ptr,324,0)
        DEF_FIELD(struct net_device,dn_ptr,325,0)
        DEF_FIELD(struct net_device,ip6_ptr,326,0)
        DEF_FIELD(struct net_device,ec_ptr,327,0)
        DEF_FIELD(struct net_device,ax25_ptr,328,0)
        DEF_FIELD(struct net_device,ieee80211_ptr,329,0)
        DEF_FIELD(struct net_device,last_rx,330,0)
        DEF_FIELD(struct net_device,dev_addr,331,0)
        DEF_FIELD(struct net_device,dev_addrs,332,0)
        DEF_FIELD(struct net_device,broadcast,333,0)
        DEF_FIELD(struct net_device,rx_queue,334,0)
        DEF_FIELD(struct net_device,_tx,335,0)
        DEF_FIELD(struct net_device,num_tx_queues,336,0)
        DEF_FIELD(struct net_device,real_num_tx_queues,337,0)
        DEF_FIELD(struct net_device,qdisc,338,0)
        DEF_FIELD(struct net_device,tx_queue_len,339,0)
        DEF_FIELD(struct net_device,tx_global_lock,340,0)
        DEF_FIELD(struct net_device,trans_start,341,0)
        DEF_FIELD(struct net_device,watchdog_timeo,342,0)
        DEF_FIELD(struct net_device,watchdog_timer,343,0)
        DEF_FIELD(struct net_device,refcnt,344,0)
        DEF_FIELD(struct net_device,todo_list,345,0)
        DEF_FIELD(struct net_device,index_hlist,346,0)
        DEF_FIELD(struct net_device,link_watch_next,347,0)
        DEF_FIELD(struct net_device,reg_state,348,0)
        DEF_FIELD(struct net_device,destructor,349,0)
        DEF_FIELD(struct net_device,npinfo,350,0)
        DEF_FIELD(struct net_device,ml_priv,351,0)
        DEF_FIELD(struct net_device,br_port,352,0)
        DEF_FIELD(struct net_device,macvlan_port,353,0)
        DEF_FIELD(struct net_device,garp_port,354,0)
        DEF_FIELD(struct net_device,dev,355,0)
        DEF_FIELD(struct net_device,sysfs_groups,356,0)
        DEF_FIELD(struct net_device,rtnl_link_ops,357,0)
        DEF_FIELD(struct net_device,vlan_features,358,0)
        DEF_FIELD(struct net_device,gso_max_size,359,0)
        DEF_FIELD(struct net_device,dcbnl_ops,360,0)
        DEF_FIELD(struct net_device,fcoe_ddp_xid,361,0)
    END_TYPE

    DEF_TYPE(struct dev_pm_ops)
        DEF_FIELD(struct dev_pm_ops,prepare,362,1)
        DEF_FIELD(struct dev_pm_ops,complete,363,0)
        DEF_FIELD(struct dev_pm_ops,suspend,364,0)
        DEF_FIELD(struct dev_pm_ops,resume,365,0)
        DEF_FIELD(struct dev_pm_ops,freeze,366,0)
        DEF_FIELD(struct dev_pm_ops,thaw,367,0)
        DEF_FIELD(struct dev_pm_ops,poweroff,368,0)
        DEF_FIELD(struct dev_pm_ops,restore,369,0)
        DEF_FIELD(struct dev_pm_ops,suspend_noirq,370,0)
        DEF_FIELD(struct dev_pm_ops,resume_noirq,371,0)
        DEF_FIELD(struct dev_pm_ops,freeze_noirq,372,0)
        DEF_FIELD(struct dev_pm_ops,thaw_noirq,373,0)
        DEF_FIELD(struct dev_pm_ops,poweroff_noirq,374,0)
        DEF_FIELD(struct dev_pm_ops,restore_noirq,375,0)
        DEF_FIELD(struct dev_pm_ops,runtime_suspend,376,0)
        DEF_FIELD(struct dev_pm_ops,runtime_resume,377,0)
        DEF_FIELD(struct dev_pm_ops,runtime_idle,378,0)
    END_TYPE

    DEF_TYPE(struct device_driver)
        DEF_FIELD(struct device_driver,name,379,1)
        DEF_FIELD(struct device_driver,bus,380,0)
        DEF_FIELD(struct device_driver,owner,381,0)
        DEF_FIELD(struct device_driver,mod_name,382,0)
        DEF_FIELD(struct device_driver,suppress_bind_attrs,383,0)
        DEF_FIELD(struct device_driver,probe,384,0)
        DEF_FIELD(struct device_driver,remove,385,0)
        DEF_FIELD(struct device_driver,shutdown,386,0)
        DEF_FIELD(struct device_driver,suspend,387,0)
        DEF_FIELD(struct device_driver,resume,388,0)
        DEF_FIELD(struct device_driver,groups,389,0)
        DEF_FIELD(struct device_driver,pm,390,0)
        DEF_FIELD(struct device_driver,p,391,0)
    END_TYPE

    DEF_TYPE(struct hlist_head)
        DEF_FIELD(struct hlist_head,first,394,1)
    END_TYPE

    DEF_TYPE(struct resource)
        DEF_FIELD(struct resource,start,397,1)
        DEF_FIELD(struct resource,end,398,0)
        DEF_FIELD(struct resource,name,399,0)
        DEF_FIELD(struct resource,flags,400,0)
        DEF_FIELD(struct resource,parent,401,0)
        DEF_FIELD(struct resource,sibling,402,0)
        DEF_FIELD(struct resource,child,403,0)
    END_TYPE

    DEF_TYPE(struct device_dma_parameters)
        DEF_FIELD(struct device_dma_parameters,max_segment_size,404,1)
        DEF_FIELD(struct device_dma_parameters,segment_boundary_mask,405,0)
    END_TYPE

    DEF_TYPE(struct pci_dev)
        DEF_FIELD(struct pci_dev,bus_list,407,1)
        DEF_FIELD(struct pci_dev,bus,408,0)
        DEF_FIELD(struct pci_dev,subordinate,409,0)
        DEF_FIELD(struct pci_dev,sysdata,410,0)
        DEF_FIELD(struct pci_dev,procent,411,0)
        DEF_FIELD(struct pci_dev,slot,412,0)
        DEF_FIELD(struct pci_dev,devfn,413,0)
        DEF_FIELD(struct pci_dev,vendor,414,0)
        DEF_FIELD(struct pci_dev,device,415,0)
        DEF_FIELD(struct pci_dev,subsystem_vendor,416,0)
        DEF_FIELD(struct pci_dev,subsystem_device,417,0)
        DEF_FIELD(struct pci_dev,class_ele,418,0)
        DEF_FIELD(struct pci_dev,revision,419,0)
        DEF_FIELD(struct pci_dev,hdr_type,420,0)
        DEF_FIELD(struct pci_dev,pcie_type,421,0)
        DEF_FIELD(struct pci_dev,rom_base_reg,422,0)
        DEF_FIELD(struct pci_dev,pin,423,0)
        DEF_FIELD(struct pci_dev,driver,424,0)
        DEF_FIELD(struct pci_dev,dma_mask,425,0)
        DEF_FIELD(struct pci_dev,dma_parms,426,0)
        DEF_FIELD(struct pci_dev,current_state,427,0)
        DEF_FIELD(struct pci_dev,pm_cap,428,0)
        DEF_FIELD(struct pci_dev,pme_support,429,0)
        DEF_FIELD(struct pci_dev,d1_support,430,0)
        DEF_FIELD(struct pci_dev,d2_support,431,0)
        DEF_FIELD(struct pci_dev,no_d1d2,432,0)
        DEF_FIELD(struct pci_dev,wakeup_prepared,433,0)
        DEF_FIELD(struct pci_dev,error_state,434,0)
        DEF_FIELD(struct pci_dev,dev,435,0)
        DEF_FIELD(struct pci_dev,cfg_size,436,0)
        DEF_FIELD(struct pci_dev,irq,437,0)
        DEF_FIELD(struct pci_dev,resource,438,0)
        DEF_FIELD(struct pci_dev,transparent,439,0)
        DEF_FIELD(struct pci_dev,multifunction,440,0)
        DEF_FIELD(struct pci_dev,is_added,441,0)
        DEF_FIELD(struct pci_dev,is_busmaster,442,0)
        DEF_FIELD(struct pci_dev,no_msi,443,0)
        DEF_FIELD(struct pci_dev,block_ucfg_access,444,0)
        DEF_FIELD(struct pci_dev,broken_parity_status,445,0)
        DEF_FIELD(struct pci_dev,irq_reroute_variant,446,0)
        DEF_FIELD(struct pci_dev,msi_enabled,447,0)
        DEF_FIELD(struct pci_dev,msix_enabled,448,0)
        DEF_FIELD(struct pci_dev,ari_enabled,449,0)
        DEF_FIELD(struct pci_dev,is_managed,450,0)
        DEF_FIELD(struct pci_dev,is_pcie,451,0)
        DEF_FIELD(struct pci_dev,needs_freset,452,0)
        DEF_FIELD(struct pci_dev,state_saved,453,0)
        DEF_FIELD(struct pci_dev,is_physfn,454,0)
        DEF_FIELD(struct pci_dev,is_virtfn,455,0)
        DEF_FIELD(struct pci_dev,reset_fn,456,0)
        DEF_FIELD(struct pci_dev,is_hotplug_bridge,457,0)
        DEF_FIELD(struct pci_dev,dev_flags,458,0)
        DEF_FIELD(struct pci_dev,enable_cnt,459,0)
        DEF_FIELD(struct pci_dev,saved_config_space,460,0)
        DEF_FIELD(struct pci_dev,saved_cap_space,461,0)
        DEF_FIELD(struct pci_dev,rom_attr,462,0)
        DEF_FIELD(struct pci_dev,rom_attr_enabled,463,0)
        DEF_FIELD(struct pci_dev,res_attr,464,0)
        DEF_FIELD(struct pci_dev,res_attr_wc,465,0)
        DEF_FIELD(struct pci_dev,msi_list,466,0)
        DEF_FIELD(struct pci_dev,vpd,467,0)
        DEF_FIELD(struct pci_dev,sriov,468,0)
        DEF_FIELD(struct pci_dev,physfn,469,0)
        DEF_FIELD(struct pci_dev,ats,470,0)
    END_TYPE

    DEF_TYPE(struct pci_driver)
        DEF_FIELD(struct pci_driver,node,471,1)
        DEF_FIELD(struct pci_driver,name,472,0)
        DEF_FIELD(struct pci_driver,id_table,473,0)
        DEF_FIELD(struct pci_driver,probe,474,0)
        DEF_FIELD(struct pci_driver,remove,475,0)
        DEF_FIELD(struct pci_driver,suspend,476,0)
        DEF_FIELD(struct pci_driver,suspend_late,477,0)
        DEF_FIELD(struct pci_driver,resume_early,478,0)
        DEF_FIELD(struct pci_driver,resume,479,0)
        DEF_FIELD(struct pci_driver,shutdown,480,0)
        DEF_FIELD(struct pci_driver,err_handler,481,0)
        DEF_FIELD(struct pci_driver,driver,482,0)
        DEF_FIELD(struct pci_driver,dynids,483,0)
    END_TYPE

    DEF_TYPE(struct pci_error_handlers)
        DEF_FIELD(struct pci_error_handlers,error_detected,484,1)
        DEF_FIELD(struct pci_error_handlers,mmio_enabled,485,0)
        DEF_FIELD(struct pci_error_handlers,link_reset,486,0)
        DEF_FIELD(struct pci_error_handlers,slot_reset,487,0)
        DEF_FIELD(struct pci_error_handlers,resume,488,0)
    END_TYPE

    DEF_TYPE(struct delayed_work)
        DEF_FIELD(struct delayed_work,work,489,1)
        DEF_FIELD(struct delayed_work,timer,490,0)
    END_TYPE

    DEF_TYPE(struct mutex)
        DEF_FIELD(struct mutex,count,491,1)
        DEF_FIELD(struct mutex,wait_lock,492,0)
        DEF_FIELD(struct mutex,wait_list,493,0)
        DEF_FIELD(struct mutex,owner,494,0)
    END_TYPE

    DEF_TYPE(struct mii_bus)
        DEF_FIELD(struct mii_bus,name,495,1)
        DEF_FIELD(struct mii_bus,id,496,0)
        DEF_FIELD(struct mii_bus,priv,497,0)
        DEF_FIELD(struct mii_bus,read,498,0)
        DEF_FIELD(struct mii_bus,write,499,0)
        DEF_FIELD(struct mii_bus,reset,500,0)
        DEF_FIELD(struct mii_bus,mdio_lock,501,0)
        DEF_FIELD(struct mii_bus,parent,502,0)
        DEF_FIELD(struct mii_bus,state,503,0)
        DEF_FIELD(struct mii_bus,dev,504,0)
        DEF_FIELD(struct mii_bus,phy_map,505,0)
        DEF_FIELD(struct mii_bus,phy_mask,506,0)
        DEF_FIELD(struct mii_bus,irq,507,0)
    END_TYPE

    DEF_TYPE(struct phy_driver)
        DEF_FIELD(struct phy_driver,phy_id,508,1)
        DEF_FIELD(struct phy_driver,name,509,0)
        DEF_FIELD(struct phy_driver,phy_id_mask,510,0)
        DEF_FIELD(struct phy_driver,features,511,0)
        DEF_FIELD(struct phy_driver,flags,512,0)
        DEF_FIELD(struct phy_driver,config_init,513,0)
        DEF_FIELD(struct phy_driver,probe,514,0)
        DEF_FIELD(struct phy_driver,suspend,515,0)
        DEF_FIELD(struct phy_driver,resume,516,0)
        DEF_FIELD(struct phy_driver,config_aneg,517,0)
        DEF_FIELD(struct phy_driver,read_status,518,0)
        DEF_FIELD(struct phy_driver,ack_interrupt,519,0)
        DEF_FIELD(struct phy_driver,config_intr,520,0)
        DEF_FIELD(struct phy_driver,did_interrupt,521,0)
        DEF_FIELD(struct phy_driver,remove,522,0)
        DEF_FIELD(struct phy_driver,driver,523,0)
    END_TYPE

    DEF_TYPE(struct phy_device)
        DEF_FIELD(struct phy_device,drv,524,1)
        DEF_FIELD(struct phy_device,bus,525,0)
        DEF_FIELD(struct phy_device,dev,526,0)
        DEF_FIELD(struct phy_device,phy_id,527,0)
        DEF_FIELD(struct phy_device,state,528,0)
        DEF_FIELD(struct phy_device,dev_flags,529,0)
        DEF_FIELD(struct phy_device,interface,530,0)
        DEF_FIELD(struct phy_device,addr,531,0)
        DEF_FIELD(struct phy_device,speed,532,0)
        DEF_FIELD(struct phy_device,duplex,533,0)
        DEF_FIELD(struct phy_device,pause,534,0)
        DEF_FIELD(struct phy_device,asym_pause,535,0)
        DEF_FIELD(struct phy_device,link,536,0)
        DEF_FIELD(struct phy_device,interrupts,537,0)
        DEF_FIELD(struct phy_device,supported,538,0)
        DEF_FIELD(struct phy_device,advertising,539,0)
        DEF_FIELD(struct phy_device,autoneg,540,0)
        DEF_FIELD(struct phy_device,link_timeout,541,0)
        DEF_FIELD(struct phy_device,irq,542,0)
        DEF_FIELD(struct phy_device,priv,543,0)
        DEF_FIELD(struct phy_device,phy_queue,544,0)
        DEF_FIELD(struct phy_device,state_queue,545,0)
        DEF_FIELD(struct phy_device,irq_disable,546,0)
        DEF_FIELD(struct phy_device,lock,547,0)
        DEF_FIELD(struct phy_device,attached_dev,548,0)
        DEF_FIELD(struct phy_device,adjust_link,549,0)
        DEF_FIELD(struct phy_device,adjust_state,550,0)
    END_TYPE

    DEF_TYPE(struct napi_struct)
        DEF_FIELD(struct napi_struct,poll_list,551,1)
        DEF_FIELD(struct napi_struct,state,552,0)
        DEF_FIELD(struct napi_struct,weight,553,0)
        DEF_FIELD(struct napi_struct,poll,554,0)
        DEF_FIELD(struct napi_struct,poll_lock,555,0)
        DEF_FIELD(struct napi_struct,poll_owner,556,0)
        DEF_FIELD(struct napi_struct,gro_count,557,0)
        DEF_FIELD(struct napi_struct,dev,558,0)
        DEF_FIELD(struct napi_struct,dev_list,559,0)
        DEF_FIELD(struct napi_struct,gro_list,560,0)
        DEF_FIELD(struct napi_struct,skb,561,0)
    END_TYPE

    DEF_TYPE(struct drv_dev_and_id)
        DEF_FIELD(struct drv_dev_and_id,drv,693,1)
        DEF_FIELD(struct drv_dev_and_id,dev,694,0)
        DEF_FIELD(struct drv_dev_and_id,id,695,0)
    END_TYPE

    DEF_TYPE(struct completion)
        DEF_FIELD(struct completion,done,769,1)
        DEF_FIELD(struct completion,wait,770,0)
    END_TYPE

    DEF_TYPE(struct xenstore_domain_interface)
        DEF_FIELD(struct xenstore_domain_interface,req,773,1)
        DEF_FIELD(struct xenstore_domain_interface,rsp,774,0)
        DEF_FIELD(struct xenstore_domain_interface,req_cons,775,0)
        DEF_FIELD(struct xenstore_domain_interface,req_prod,776,0)
        DEF_FIELD(struct xenstore_domain_interface,rsp_cons,777,0)
        DEF_FIELD(struct xenstore_domain_interface,rsp_prod,778,0)
    END_TYPE

    DEF_TYPE(struct xenbus_watch)
        DEF_FIELD(struct xenbus_watch,list,779,1)
        DEF_FIELD(struct xenbus_watch,node,780,0)
        DEF_FIELD(struct xenbus_watch,callback,781,0)
    END_TYPE

    DEF_TYPE(struct xenbus_device)
        DEF_FIELD(struct xenbus_device,devicetype,782,1)
        DEF_FIELD(struct xenbus_device,nodename,783,0)
        DEF_FIELD(struct xenbus_device,otherend,784,0)
        DEF_FIELD(struct xenbus_device,otherend_id,785,0)
        DEF_FIELD(struct xenbus_device,otherend_watch,786,0)
        DEF_FIELD(struct xenbus_device,dev,787,0)
        DEF_FIELD(struct xenbus_device,state,788,0)
        DEF_FIELD(struct xenbus_device,down,789,0)
    END_TYPE

    DEF_TYPE(struct xenbus_device_id)
        DEF_FIELD(struct xenbus_device_id,devicetype,790,1)
    END_TYPE

    DEF_TYPE(struct xenbus_driver)
        DEF_FIELD(struct xenbus_driver,name,791,1)
        DEF_FIELD(struct xenbus_driver,owner,792,0)
        DEF_FIELD(struct xenbus_driver,ids,793,0)
        DEF_FIELD(struct xenbus_driver,probe,794,0)
        DEF_FIELD(struct xenbus_driver,otherend_changed,795,0)
        DEF_FIELD(struct xenbus_driver,remove,796,0)
        DEF_FIELD(struct xenbus_driver,suspend,797,0)
        DEF_FIELD(struct xenbus_driver,resume,798,0)
        DEF_FIELD(struct xenbus_driver,uevent,799,0)
        DEF_FIELD(struct xenbus_driver,driver,800,0)
        DEF_FIELD(struct xenbus_driver,read_otherend_details,801,0)
        DEF_FIELD(struct xenbus_driver,is_ready,802,0)
    END_TYPE

    DEF_TYPE(struct xenbus_transaction)
        DEF_FIELD(struct xenbus_transaction,id,803,1)
    END_TYPE

    DEF_TYPE(struct xb_find_info)
        DEF_FIELD(struct xb_find_info,dev,838,1)
        DEF_FIELD(struct xb_find_info,nodename,839,0)
    END_TYPE

    DEF_TYPE(struct mii_if_info)
        DEF_FIELD(struct mii_if_info,phy_id,847,1)
        DEF_FIELD(struct mii_if_info,advertising,848,0)
        DEF_FIELD(struct mii_if_info,phy_id_mask,849,0)
        DEF_FIELD(struct mii_if_info,reg_num_mask,850,0)
        DEF_FIELD(struct mii_if_info,full_duplex,851,0)
        DEF_FIELD(struct mii_if_info,force_media,852,0)
        DEF_FIELD(struct mii_if_info,supports_gmii,853,0)
        DEF_FIELD(struct mii_if_info,dev,854,0)
        DEF_FIELD(struct mii_if_info,mdio_read,855,0)
        DEF_FIELD(struct mii_if_info,mdio_write,856,0)
    END_TYPE

    DEF_TYPE(struct phy_fixup)
        DEF_FIELD(struct phy_fixup,list,857,1)
        DEF_FIELD(struct phy_fixup,bus_id,858,0)
        DEF_FIELD(struct phy_fixup,phy_uid,859,0)
        DEF_FIELD(struct phy_fixup,phy_uid_mask,860,0)
        DEF_FIELD(struct phy_fixup,run,861,0)
    END_TYPE

    DEF_TYPE(struct phy_setting)
        DEF_FIELD(struct phy_setting,speed,865,1)
        DEF_FIELD(struct phy_setting,duplex,866,0)
        DEF_FIELD(struct phy_setting,setting,867,0)
    END_TYPE

    DEF_TYPE(raw_rwlock_t)
        DEF_FIELD(raw_rwlock_t,lock,935,1)
    END_TYPE

    DEF_TYPE(rwlock_t)
        DEF_FIELD(rwlock_t,raw_lock,936,1)
    END_TYPE

    DEF_TYPE(struct elf64_sym)
        DEF_FIELD(struct elf64_sym,st_name,957,1)
        DEF_FIELD(struct elf64_sym,st_info,958,0)
        DEF_FIELD(struct elf64_sym,st_other,959,0)
        DEF_FIELD(struct elf64_sym,st_shndx,960,0)
        DEF_FIELD(struct elf64_sym,st_value,961,0)
        DEF_FIELD(struct elf64_sym,st_size,962,0)
    END_TYPE

    DEF_TYPE(struct timespec)
        DEF_FIELD(struct timespec,tv_sec,968,1)
        DEF_FIELD(struct timespec,tv_nsec,969,0)
    END_TYPE

    DEF_TYPE(struct rw_semaphore)
        DEF_FIELD(struct rw_semaphore,count,970,1)
        DEF_FIELD(struct rw_semaphore,wait_lock,971,0)
        DEF_FIELD(struct rw_semaphore,wait_list,972,0)
    END_TYPE

    DEF_TYPE(struct radix_tree_root)
        DEF_FIELD(struct radix_tree_root,height,973,1)
        DEF_FIELD(struct radix_tree_root,gfp_mask,974,0)
        DEF_FIELD(struct radix_tree_root,rnode,975,0)
    END_TYPE

    DEF_TYPE(struct kmem_cache_order_objects)
        DEF_FIELD(struct kmem_cache_order_objects,x,976,1)
    END_TYPE

    DEF_TYPE(struct kmem_cache_node)
        DEF_FIELD(struct kmem_cache_node,list_lock,977,1)
        DEF_FIELD(struct kmem_cache_node,nr_partial,978,0)
        DEF_FIELD(struct kmem_cache_node,partial,979,0)
        DEF_FIELD(struct kmem_cache_node,nr_slabs,980,0)
        DEF_FIELD(struct kmem_cache_node,total_objects,981,0)
        DEF_FIELD(struct kmem_cache_node,full,982,0)
    END_TYPE

    DEF_TYPE(struct kmem_cache)
        DEF_FIELD(struct kmem_cache,flags,983,1)
        DEF_FIELD(struct kmem_cache,size,984,0)
        DEF_FIELD(struct kmem_cache,objsize,985,0)
        DEF_FIELD(struct kmem_cache,offset,986,0)
        DEF_FIELD(struct kmem_cache,oo,987,0)
        DEF_FIELD(struct kmem_cache,local_node,988,0)
        DEF_FIELD(struct kmem_cache,max,989,0)
        DEF_FIELD(struct kmem_cache,min,990,0)
        DEF_FIELD(struct kmem_cache,allocflags,991,0)
        DEF_FIELD(struct kmem_cache,refcount,992,0)
        DEF_FIELD(struct kmem_cache,ctor,993,0)
        DEF_FIELD(struct kmem_cache,inuse,994,0)
        DEF_FIELD(struct kmem_cache,align,995,0)
        DEF_FIELD(struct kmem_cache,min_partial,996,0)
        DEF_FIELD(struct kmem_cache,name,997,0)
        DEF_FIELD(struct kmem_cache,list,998,0)
        DEF_FIELD(struct kmem_cache,kobj,999,0)
        DEF_FIELD(struct kmem_cache,remote_node_defrag_ratio,1000,0)
        DEF_FIELD(struct kmem_cache,node,1001,0)
        DEF_FIELD(struct kmem_cache,cpu_slab,1002,0)
    END_TYPE

    DEF_TYPE(struct page)
        DEF_FIELD(struct page,flags,1003,1)
        DEF_FIELD(struct page,_count,1004,0)
        DEF_FIELD(struct page,_mapcount,1005,0)
        DEF_FIELD(struct page,inuse,1006,0)
        DEF_FIELD(struct page,objects,1007,0)
        DEF_FIELD(struct page,private_data,1008,0)
        DEF_FIELD(struct page,mapping,1009,0)
        DEF_FIELD(struct page,ptl,1010,0)
        DEF_FIELD(struct page,slab,1011,0)
        DEF_FIELD(struct page,first_page,1012,0)
        DEF_FIELD(struct page,index,1013,0)
        DEF_FIELD(struct page,freelist,1014,0)
        DEF_FIELD(struct page,lru,1015,0)
    END_TYPE

    DEF_TYPE(struct prio_tree_root)
        DEF_FIELD(struct prio_tree_root,prio_tree_node,1016,1)
        DEF_FIELD(struct prio_tree_root,index_bits,1017,0)
        DEF_FIELD(struct prio_tree_root,raw,1018,0)
    END_TYPE

    DEF_TYPE(read_descriptor_t)
        DEF_FIELD(read_descriptor_t,written,1019,1)
        DEF_FIELD(read_descriptor_t,count,1020,0)
        DEF_FIELD(read_descriptor_t,arg,1023,0)
        DEF_FIELD(read_descriptor_t,error,1024,0)
    END_TYPE

    DEF_TYPE(struct address_space_operations)
        DEF_FIELD(struct address_space_operations,writepage,1025,1)
        DEF_FIELD(struct address_space_operations,readpage,1026,0)
        DEF_FIELD(struct address_space_operations,sync_page,1027,0)
        DEF_FIELD(struct address_space_operations,writepages,1028,0)
        DEF_FIELD(struct address_space_operations,set_page_dirty,1029,0)
        DEF_FIELD(struct address_space_operations,readpages,1030,0)
        DEF_FIELD(struct address_space_operations,write_begin,1031,0)
        DEF_FIELD(struct address_space_operations,write_end,1032,0)
        DEF_FIELD(struct address_space_operations,bmap,1033,0)
        DEF_FIELD(struct address_space_operations,invalidatepage,1034,0)
        DEF_FIELD(struct address_space_operations,releasepage,1035,0)
        DEF_FIELD(struct address_space_operations,direct_IO,1036,0)
        DEF_FIELD(struct address_space_operations,get_xip_mem,1037,0)
        DEF_FIELD(struct address_space_operations,migratepage,1038,0)
        DEF_FIELD(struct address_space_operations,launder_page,1039,0)
        DEF_FIELD(struct address_space_operations,is_partially_uptodate,1040,0)
        DEF_FIELD(struct address_space_operations,error_remove_page,1041,0)
    END_TYPE

    DEF_TYPE(struct address_space)
        DEF_FIELD(struct address_space,host,1042,1)
        DEF_FIELD(struct address_space,page_tree,1043,0)
        DEF_FIELD(struct address_space,tree_lock,1044,0)
        DEF_FIELD(struct address_space,i_mmap_writable,1045,0)
        DEF_FIELD(struct address_space,i_mmap,1046,0)
        DEF_FIELD(struct address_space,i_mmap_nonlinear,1047,0)
        DEF_FIELD(struct address_space,i_mmap_lock,1048,0)
        DEF_FIELD(struct address_space,truncate_count,1049,0)
        DEF_FIELD(struct address_space,nrpages,1050,0)
        DEF_FIELD(struct address_space,writeback_index,1051,0)
        DEF_FIELD(struct address_space,a_ops,1052,0)
        DEF_FIELD(struct address_space,flags,1053,0)
        DEF_FIELD(struct address_space,backing_dev_info,1054,0)
        DEF_FIELD(struct address_space,private_lock,1055,0)
        DEF_FIELD(struct address_space,private_list,1056,0)
        DEF_FIELD(struct address_space,assoc_mapping,1057,0)
    END_TYPE

    DEF_TYPE(struct mem_dqinfo)
        DEF_FIELD(struct mem_dqinfo,dqi_format,1058,1)
        DEF_FIELD(struct mem_dqinfo,dqi_fmt_id,1059,0)
        DEF_FIELD(struct mem_dqinfo,dqi_dirty_list,1060,0)
        DEF_FIELD(struct mem_dqinfo,dqi_flags,1061,0)
        DEF_FIELD(struct mem_dqinfo,dqi_bgrace,1062,0)
        DEF_FIELD(struct mem_dqinfo,dqi_igrace,1063,0)
        DEF_FIELD(struct mem_dqinfo,dqi_maxblimit,1064,0)
        DEF_FIELD(struct mem_dqinfo,dqi_maxilimit,1065,0)
        DEF_FIELD(struct mem_dqinfo,dqi_priv,1066,0)
    END_TYPE

    DEF_TYPE(struct quota_info)
        DEF_FIELD(struct quota_info,flags,1067,1)
        DEF_FIELD(struct quota_info,dqio_mutex,1068,0)
        DEF_FIELD(struct quota_info,dqonoff_mutex,1069,0)
        DEF_FIELD(struct quota_info,dqptr_sem,1070,0)
        DEF_FIELD(struct quota_info,files,1071,0)
        DEF_FIELD(struct quota_info,info,1072,0)
        DEF_FIELD(struct quota_info,ops,1073,0)
    END_TYPE

    DEF_TYPE(struct lock_class_key)
    END_TYPE

    DEF_TYPE(struct file_system_type)
        DEF_FIELD(struct file_system_type,name,1074,1)
        DEF_FIELD(struct file_system_type,fs_flags,1075,0)
        DEF_FIELD(struct file_system_type,get_sb,1076,0)
        DEF_FIELD(struct file_system_type,kill_sb,1077,0)
        DEF_FIELD(struct file_system_type,owner,1078,0)
        DEF_FIELD(struct file_system_type,next,1079,0)
        DEF_FIELD(struct file_system_type,fs_supers,1080,0)
        DEF_FIELD(struct file_system_type,s_lock_key,1081,0)
        DEF_FIELD(struct file_system_type,s_umount_key,1082,0)
        DEF_FIELD(struct file_system_type,i_lock_key,1083,0)
        DEF_FIELD(struct file_system_type,i_mutex_key,1084,0)
        DEF_FIELD(struct file_system_type,i_mutex_dir_key,1085,0)
        DEF_FIELD(struct file_system_type,i_alloc_sem_key,1086,0)
    END_TYPE

    DEF_TYPE(struct super_operations)
        DEF_FIELD(struct super_operations,alloc_inode,1087,1)
        DEF_FIELD(struct super_operations,destroy_inode,1088,0)
        DEF_FIELD(struct super_operations,dirty_inode,1089,0)
        DEF_FIELD(struct super_operations,write_inode,1090,0)
        DEF_FIELD(struct super_operations,drop_inode,1091,0)
        DEF_FIELD(struct super_operations,delete_inode,1092,0)
        DEF_FIELD(struct super_operations,put_super,1093,0)
        DEF_FIELD(struct super_operations,write_super,1094,0)
        DEF_FIELD(struct super_operations,sync_fs,1095,0)
        DEF_FIELD(struct super_operations,freeze_fs,1096,0)
        DEF_FIELD(struct super_operations,unfreeze_fs,1097,0)
        DEF_FIELD(struct super_operations,statfs,1098,0)
        DEF_FIELD(struct super_operations,remount_fs,1099,0)
        DEF_FIELD(struct super_operations,clear_inode,1100,0)
        DEF_FIELD(struct super_operations,umount_begin,1101,0)
        DEF_FIELD(struct super_operations,show_options,1102,0)
        DEF_FIELD(struct super_operations,show_stats,1103,0)
        DEF_FIELD(struct super_operations,quota_read,1104,0)
        DEF_FIELD(struct super_operations,quota_write,1105,0)
        DEF_FIELD(struct super_operations,bdev_try_to_free_page,1106,0)
    END_TYPE

    DEF_TYPE(struct dquot_operations)
        DEF_FIELD(struct dquot_operations,initialize,1107,1)
        DEF_FIELD(struct dquot_operations,drop,1108,0)
        DEF_FIELD(struct dquot_operations,alloc_space,1109,0)
        DEF_FIELD(struct dquot_operations,alloc_inode,1110,0)
        DEF_FIELD(struct dquot_operations,free_space,1111,0)
        DEF_FIELD(struct dquot_operations,free_inode,1112,0)
        DEF_FIELD(struct dquot_operations,transfer,1113,0)
        DEF_FIELD(struct dquot_operations,write_dquot,1114,0)
        DEF_FIELD(struct dquot_operations,alloc_dquot,1115,0)
        DEF_FIELD(struct dquot_operations,destroy_dquot,1116,0)
        DEF_FIELD(struct dquot_operations,acquire_dquot,1117,0)
        DEF_FIELD(struct dquot_operations,release_dquot,1118,0)
        DEF_FIELD(struct dquot_operations,mark_dirty,1119,0)
        DEF_FIELD(struct dquot_operations,write_info,1120,0)
        DEF_FIELD(struct dquot_operations,reserve_space,1121,0)
        DEF_FIELD(struct dquot_operations,claim_space,1122,0)
        DEF_FIELD(struct dquot_operations,release_rsv,1123,0)
        DEF_FIELD(struct dquot_operations,get_reserved_space,1124,0)
    END_TYPE

    DEF_TYPE(struct quotactl_ops)
        DEF_FIELD(struct quotactl_ops,quota_on,1125,1)
        DEF_FIELD(struct quotactl_ops,quota_off,1126,0)
        DEF_FIELD(struct quotactl_ops,quota_sync,1127,0)
        DEF_FIELD(struct quotactl_ops,get_info,1128,0)
        DEF_FIELD(struct quotactl_ops,set_info,1129,0)
        DEF_FIELD(struct quotactl_ops,get_dqblk,1130,0)
        DEF_FIELD(struct quotactl_ops,set_dqblk,1131,0)
        DEF_FIELD(struct quotactl_ops,get_xstate,1132,0)
        DEF_FIELD(struct quotactl_ops,set_xstate,1133,0)
        DEF_FIELD(struct quotactl_ops,get_xquota,1134,0)
        DEF_FIELD(struct quotactl_ops,set_xquota,1135,0)
    END_TYPE

    DEF_TYPE(struct export_operations)
        DEF_FIELD(struct export_operations,encode_fh,1136,1)
        DEF_FIELD(struct export_operations,fh_to_dentry,1137,0)
        DEF_FIELD(struct export_operations,fh_to_parent,1138,0)
        DEF_FIELD(struct export_operations,get_name,1139,0)
        DEF_FIELD(struct export_operations,get_parent,1140,0)
    END_TYPE

    DEF_TYPE(struct xattr_handler)
        DEF_FIELD(struct xattr_handler,prefix,1141,1)
        DEF_FIELD(struct xattr_handler,list,1142,0)
        DEF_FIELD(struct xattr_handler,get,1143,0)
        DEF_FIELD(struct xattr_handler,set,1144,0)
    END_TYPE

    DEF_TYPE(struct rcu_head)
        DEF_FIELD(struct rcu_head,next,1145,1)
        DEF_FIELD(struct rcu_head,func,1146,0)
    END_TYPE

    DEF_TYPE(struct qstr)
        DEF_FIELD(struct qstr,hash,1147,1)
        DEF_FIELD(struct qstr,len,1148,0)
        DEF_FIELD(struct qstr,name,1149,0)
    END_TYPE

    DEF_TYPE(struct dentry)
        DEF_FIELD(struct dentry,d_count,1150,1)
        DEF_FIELD(struct dentry,d_flags,1151,0)
        DEF_FIELD(struct dentry,d_lock,1152,0)
        DEF_FIELD(struct dentry,d_mounted,1153,0)
        DEF_FIELD(struct dentry,d_inode,1154,0)
        DEF_FIELD(struct dentry,d_hash,1155,0)
        DEF_FIELD(struct dentry,d_parent,1156,0)
        DEF_FIELD(struct dentry,d_name,1157,0)
        DEF_FIELD(struct dentry,d_lru,1158,0)
        DEF_FIELD(struct dentry,d_u,1161,0)
        DEF_FIELD(struct dentry,d_subdirs,1162,0)
        DEF_FIELD(struct dentry,d_alias,1163,0)
        DEF_FIELD(struct dentry,d_time,1164,0)
        DEF_FIELD(struct dentry,d_op,1165,0)
        DEF_FIELD(struct dentry,d_sb,1166,0)
        DEF_FIELD(struct dentry,d_fsdata,1167,0)
        DEF_FIELD(struct dentry,d_iname,1168,0)
    END_TYPE

    DEF_TYPE(struct super_block)
        DEF_FIELD(struct super_block,s_list,1169,1)
        DEF_FIELD(struct super_block,s_dev,1170,0)
        DEF_FIELD(struct super_block,s_blocksize,1171,0)
        DEF_FIELD(struct super_block,s_blocksize_bits,1172,0)
        DEF_FIELD(struct super_block,s_dirt,1173,0)
        DEF_FIELD(struct super_block,s_maxbytes,1174,0)
        DEF_FIELD(struct super_block,s_type,1175,0)
        DEF_FIELD(struct super_block,s_op,1176,0)
        DEF_FIELD(struct super_block,dq_op,1177,0)
        DEF_FIELD(struct super_block,s_qcop,1178,0)
        DEF_FIELD(struct super_block,s_export_op,1179,0)
        DEF_FIELD(struct super_block,s_flags,1180,0)
        DEF_FIELD(struct super_block,s_magic,1181,0)
        DEF_FIELD(struct super_block,s_root,1182,0)
        DEF_FIELD(struct super_block,s_umount,1183,0)
        DEF_FIELD(struct super_block,s_lock,1184,0)
        DEF_FIELD(struct super_block,s_count,1185,0)
        DEF_FIELD(struct super_block,s_need_sync,1186,0)
        DEF_FIELD(struct super_block,s_active,1187,0)
        DEF_FIELD(struct super_block,s_security,1188,0)
        DEF_FIELD(struct super_block,s_xattr,1189,0)
        DEF_FIELD(struct super_block,s_inodes,1190,0)
        DEF_FIELD(struct super_block,s_anon,1191,0)
        DEF_FIELD(struct super_block,s_files,1192,0)
        DEF_FIELD(struct super_block,s_dentry_lru,1193,0)
        DEF_FIELD(struct super_block,s_nr_dentry_unused,1194,0)
        DEF_FIELD(struct super_block,s_bdev,1195,0)
        DEF_FIELD(struct super_block,s_bdi,1196,0)
        DEF_FIELD(struct super_block,s_mtd,1197,0)
        DEF_FIELD(struct super_block,s_instances,1198,0)
        DEF_FIELD(struct super_block,s_dquot,1199,0)
        DEF_FIELD(struct super_block,s_frozen,1200,0)
        DEF_FIELD(struct super_block,s_wait_unfrozen,1201,0)
        DEF_FIELD(struct super_block,s_id,1202,0)
        DEF_FIELD(struct super_block,s_fs_info,1203,0)
        DEF_FIELD(struct super_block,s_mode,1204,0)
        DEF_FIELD(struct super_block,s_vfs_rename_mutex,1205,0)
        DEF_FIELD(struct super_block,s_time_gran,1206,0)
        DEF_FIELD(struct super_block,s_subtype,1207,0)
        DEF_FIELD(struct super_block,s_options,1208,0)
    END_TYPE

    DEF_TYPE(struct inode_operations)
        DEF_FIELD(struct inode_operations,create,1209,1)
        DEF_FIELD(struct inode_operations,lookup,1210,0)
        DEF_FIELD(struct inode_operations,link,1211,0)
        DEF_FIELD(struct inode_operations,unlink,1212,0)
        DEF_FIELD(struct inode_operations,symlink,1213,0)
        DEF_FIELD(struct inode_operations,mkdir,1214,0)
        DEF_FIELD(struct inode_operations,rmdir,1215,0)
        DEF_FIELD(struct inode_operations,mknod,1216,0)
        DEF_FIELD(struct inode_operations,rename,1217,0)
        DEF_FIELD(struct inode_operations,readlink,1218,0)
        DEF_FIELD(struct inode_operations,follow_link,1219,0)
        DEF_FIELD(struct inode_operations,put_link,1220,0)
        DEF_FIELD(struct inode_operations,truncate,1221,0)
        DEF_FIELD(struct inode_operations,permission,1222,0)
        DEF_FIELD(struct inode_operations,check_acl,1223,0)
        DEF_FIELD(struct inode_operations,setattr,1224,0)
        DEF_FIELD(struct inode_operations,getattr,1225,0)
        DEF_FIELD(struct inode_operations,setxattr,1226,0)
        DEF_FIELD(struct inode_operations,getxattr,1227,0)
        DEF_FIELD(struct inode_operations,listxattr,1228,0)
        DEF_FIELD(struct inode_operations,removexattr,1229,0)
        DEF_FIELD(struct inode_operations,truncate_range,1230,0)
        DEF_FIELD(struct inode_operations,fallocate,1231,0)
        DEF_FIELD(struct inode_operations,fiemap,1232,0)
    END_TYPE

    DEF_TYPE(struct file_operations)
        DEF_FIELD(struct file_operations,owner,1234,1)
        DEF_FIELD(struct file_operations,llseek,1235,0)
        DEF_FIELD(struct file_operations,read,1236,0)
        DEF_FIELD(struct file_operations,write,1237,0)
        DEF_FIELD(struct file_operations,aio_read,1238,0)
        DEF_FIELD(struct file_operations,aio_write,1239,0)
        DEF_FIELD(struct file_operations,readdir,1240,0)
        DEF_FIELD(struct file_operations,poll,1241,0)
        DEF_FIELD(struct file_operations,ioctl,1242,0)
        DEF_FIELD(struct file_operations,unlocked_ioctl,1243,0)
        DEF_FIELD(struct file_operations,compat_ioctl,1244,0)
        DEF_FIELD(struct file_operations,mmap,1245,0)
        DEF_FIELD(struct file_operations,open,1246,0)
        DEF_FIELD(struct file_operations,flush,1247,0)
        DEF_FIELD(struct file_operations,release,1248,0)
        DEF_FIELD(struct file_operations,fsync,1249,0)
        DEF_FIELD(struct file_operations,aio_fsync,1250,0)
        DEF_FIELD(struct file_operations,fasync,1251,0)
        DEF_FIELD(struct file_operations,lock,1252,0)
        DEF_FIELD(struct file_operations,sendpage,1253,0)
        DEF_FIELD(struct file_operations,get_unmapped_area,1254,0)
        DEF_FIELD(struct file_operations,check_flags,1255,0)
        DEF_FIELD(struct file_operations,flock,1256,0)
        DEF_FIELD(struct file_operations,splice_write,1257,0)
        DEF_FIELD(struct file_operations,splice_read,1258,0)
        DEF_FIELD(struct file_operations,setlease,1259,0)
    END_TYPE

    DEF_TYPE(struct timespec_inode)
        DEF_FIELD(struct timespec_inode,tv_sec,1261,1)
        DEF_FIELD(struct timespec_inode,tv_nsec,1262,0)
    END_TYPE

    DEF_TYPE(struct inode)
        DEF_FIELD(struct inode,i_hash,1263,1)
        DEF_FIELD(struct inode,i_list,1264,0)
        DEF_FIELD(struct inode,i_sb_list,1265,0)
        DEF_FIELD(struct inode,i_dentry,1266,0)
        DEF_FIELD(struct inode,i_ino,1267,0)
        DEF_FIELD(struct inode,i_count,1268,0)
        DEF_FIELD(struct inode,i_nlink,1269,0)
        DEF_FIELD(struct inode,i_uid,1270,0)
        DEF_FIELD(struct inode,i_gid,1271,0)
        DEF_FIELD(struct inode,i_rdev,1272,0)
        DEF_FIELD(struct inode,i_version,1273,0)
        DEF_FIELD(struct inode,i_size,1274,0)
        DEF_FIELD(struct inode,i_atime,1275,0)
        DEF_FIELD(struct inode,i_mtime,1276,0)
        DEF_FIELD(struct inode,i_ctime,1277,0)
        DEF_FIELD(struct inode,i_blocks,1278,0)
        DEF_FIELD(struct inode,i_blkbits,1279,0)
        DEF_FIELD(struct inode,i_bytes,1280,0)
        DEF_FIELD(struct inode,i_mode,1281,0)
        DEF_FIELD(struct inode,i_lock,1282,0)
        DEF_FIELD(struct inode,i_mutex,1283,0)
        DEF_FIELD(struct inode,i_alloc_sem,1284,0)
        DEF_FIELD(struct inode,i_op,1285,0)
        DEF_FIELD(struct inode,i_fop,1286,0)
        DEF_FIELD(struct inode,i_sb,1287,0)
        DEF_FIELD(struct inode,i_flock,1288,0)
        DEF_FIELD(struct inode,i_mapping,1289,0)
        DEF_FIELD(struct inode,i_data,1290,0)
        DEF_FIELD(struct inode,i_dquot,1291,0)
        DEF_FIELD(struct inode,i_devices,1292,0)
        DEF_FIELD(struct inode,i_pipe,1293,0)
        DEF_FIELD(struct inode,i_bdev,1294,0)
        DEF_FIELD(struct inode,i_cdev,1295,0)
        DEF_FIELD(struct inode,i_generation,1296,0)
        DEF_FIELD(struct inode,i_fsnotify_mask,1297,0)
        DEF_FIELD(struct inode,i_fsnotify_mark_entries,1298,0)
        DEF_FIELD(struct inode,inotify_watches,1299,0)
        DEF_FIELD(struct inode,inotify_mutex,1300,0)
        DEF_FIELD(struct inode,i_state,1301,0)
        DEF_FIELD(struct inode,dirtied_when,1302,0)
        DEF_FIELD(struct inode,i_flags,1303,0)
        DEF_FIELD(struct inode,i_writecount,1304,0)
        DEF_FIELD(struct inode,i_security,1305,0)
        DEF_FIELD(struct inode,i_acl,1306,0)
        DEF_FIELD(struct inode,i_default_acl,1307,0)
        DEF_FIELD(struct inode,i_private,1308,0)
    END_TYPE

    DEF_TYPE(struct ctl_table)
        DEF_FIELD(struct ctl_table,ctl_name,1312,1)
        DEF_FIELD(struct ctl_table,procname,1313,0)
        DEF_FIELD(struct ctl_table,data,1314,0)
        DEF_FIELD(struct ctl_table,maxlen,1315,0)
        DEF_FIELD(struct ctl_table,mode,1316,0)
        DEF_FIELD(struct ctl_table,child,1317,0)
        DEF_FIELD(struct ctl_table,parent,1318,0)
        DEF_FIELD(struct ctl_table,proc_handler,1319,0)
        DEF_FIELD(struct ctl_table,strategy,1320,0)
        DEF_FIELD(struct ctl_table,extra1,1321,0)
        DEF_FIELD(struct ctl_table,extra2,1322,0)
    END_TYPE

    DEF_TYPE(struct journal_header_s)
        DEF_FIELD(struct journal_header_s,h_magic,1324,1)
        DEF_FIELD(struct journal_header_s,h_blocktype,1325,0)
        DEF_FIELD(struct journal_header_s,h_sequence,1326,0)
    END_TYPE

    DEF_TYPE(struct journal_superblock_s)
        DEF_FIELD(struct journal_superblock_s,s_header,1327,1)
        DEF_FIELD(struct journal_superblock_s,s_blocksize,1328,0)
        DEF_FIELD(struct journal_superblock_s,s_maxlen,1329,0)
        DEF_FIELD(struct journal_superblock_s,s_first,1330,0)
        DEF_FIELD(struct journal_superblock_s,s_sequence,1331,0)
        DEF_FIELD(struct journal_superblock_s,s_start,1332,0)
        DEF_FIELD(struct journal_superblock_s,s_errno,1333,0)
        DEF_FIELD(struct journal_superblock_s,s_feature_compat,1334,0)
        DEF_FIELD(struct journal_superblock_s,s_feature_incompat,1335,0)
        DEF_FIELD(struct journal_superblock_s,s_feature_ro_compat,1336,0)
        DEF_FIELD(struct journal_superblock_s,s_uuid,1337,0)
        DEF_FIELD(struct journal_superblock_s,s_nr_users,1338,0)
        DEF_FIELD(struct journal_superblock_s,s_dynsuper,1339,0)
        DEF_FIELD(struct journal_superblock_s,s_max_transaction,1340,0)
        DEF_FIELD(struct journal_superblock_s,s_max_trans_data,1341,0)
        DEF_FIELD(struct journal_superblock_s,s_padding,1342,0)
        DEF_FIELD(struct journal_superblock_s,s_users,1343,0)
    END_TYPE

    DEF_TYPE(struct journal_s)
        DEF_FIELD(struct journal_s,j_flags,1348,1)
        DEF_FIELD(struct journal_s,j_errno,1349,0)
        DEF_FIELD(struct journal_s,j_sb_buffer,1350,0)
        DEF_FIELD(struct journal_s,j_superblock,1351,0)
        DEF_FIELD(struct journal_s,j_format_version,1352,0)
        DEF_FIELD(struct journal_s,j_state_lock,1353,0)
        DEF_FIELD(struct journal_s,j_barrier_count,1354,0)
        DEF_FIELD(struct journal_s,j_barrier,1355,0)
        DEF_FIELD(struct journal_s,j_running_transaction,1356,0)
        DEF_FIELD(struct journal_s,j_committing_transaction,1357,0)
        DEF_FIELD(struct journal_s,j_checkpoint_transactions,1358,0)
        DEF_FIELD(struct journal_s,j_wait_transaction_locked,1359,0)
        DEF_FIELD(struct journal_s,j_wait_logspace,1360,0)
        DEF_FIELD(struct journal_s,j_wait_done_commit,1361,0)
        DEF_FIELD(struct journal_s,j_wait_checkpoint,1362,0)
        DEF_FIELD(struct journal_s,j_wait_commit,1363,0)
        DEF_FIELD(struct journal_s,j_wait_updates,1364,0)
        DEF_FIELD(struct journal_s,j_checkpoint_mutex,1365,0)
        DEF_FIELD(struct journal_s,j_head,1366,0)
        DEF_FIELD(struct journal_s,j_tail,1367,0)
        DEF_FIELD(struct journal_s,j_free,1368,0)
        DEF_FIELD(struct journal_s,j_first,1369,0)
        DEF_FIELD(struct journal_s,j_last,1370,0)
        DEF_FIELD(struct journal_s,j_dev,1371,0)
        DEF_FIELD(struct journal_s,j_blocksize,1372,0)
        DEF_FIELD(struct journal_s,j_blk_offset,1373,0)
        DEF_FIELD(struct journal_s,j_fs_dev,1374,0)
        DEF_FIELD(struct journal_s,j_maxlen,1375,0)
        DEF_FIELD(struct journal_s,j_list_lock,1376,0)
        DEF_FIELD(struct journal_s,j_inode,1377,0)
        DEF_FIELD(struct journal_s,j_tail_sequence,1378,0)
        DEF_FIELD(struct journal_s,j_transaction_sequence,1379,0)
        DEF_FIELD(struct journal_s,j_commit_sequence,1380,0)
        DEF_FIELD(struct journal_s,j_commit_request,1381,0)
        DEF_FIELD(struct journal_s,j_uuid,1382,0)
        DEF_FIELD(struct journal_s,j_task,1383,0)
        DEF_FIELD(struct journal_s,j_max_transaction_buffers,1384,0)
        DEF_FIELD(struct journal_s,j_commit_interval,1385,0)
        DEF_FIELD(struct journal_s,j_commit_timer,1386,0)
        DEF_FIELD(struct journal_s,j_revoke_lock,1387,0)
        DEF_FIELD(struct journal_s,j_revoke,1388,0)
        DEF_FIELD(struct journal_s,j_revoke_table,1389,0)
        DEF_FIELD(struct journal_s,j_wbuf,1390,0)
        DEF_FIELD(struct journal_s,j_wbufsize,1391,0)
        DEF_FIELD(struct journal_s,j_last_sync_writer,1392,0)
        DEF_FIELD(struct journal_s,j_average_commit_time,1393,0)
        DEF_FIELD(struct journal_s,j_private,1394,0)
    END_TYPE

    DEF_TYPE(union input_seq_state)
        DEF_FIELD(union input_seq_state,pos,1506,1)
        DEF_FIELD(union input_seq_state,mutex_acquired,1507,0)
        DEF_FIELD(union input_seq_state,p,1508,0)
    END_TYPE

    DEF_TYPE(struct poll_table_struct)
        DEF_FIELD(struct poll_table_struct,qproc,1528,1)
        DEF_FIELD(struct poll_table_struct,key,1529,0)
    END_TYPE

    DEF_TYPE(substring_t)
        DEF_FIELD(substring_t,from,1695,1)
        DEF_FIELD(substring_t,to,1696,0)
    END_TYPE

    DEF_TYPE(__sigset_t)
        DEF_FIELD(__sigset_t,__val,1700,1)
    END_TYPE

    DEF_TYPE(struct buffer_head)
        DEF_FIELD(struct buffer_head,b_state,1704,1)
        DEF_FIELD(struct buffer_head,b_this_page,1705,0)
        DEF_FIELD(struct buffer_head,b_page,1706,0)
        DEF_FIELD(struct buffer_head,b_blocknr,1707,0)
        DEF_FIELD(struct buffer_head,b_size,1708,0)
        DEF_FIELD(struct buffer_head,b_data,1709,0)
        DEF_FIELD(struct buffer_head,b_bdev,1710,0)
        DEF_FIELD(struct buffer_head,b_end_io,1711,0)
        DEF_FIELD(struct buffer_head,b_private,1712,0)
        DEF_FIELD(struct buffer_head,b_assoc_buffers,1713,0)
        DEF_FIELD(struct buffer_head,b_assoc_map,1714,0)
        DEF_FIELD(struct buffer_head,b_count,1715,0)
    END_TYPE

    DEF_TYPE(struct mb_cache_op)
        DEF_FIELD(struct mb_cache_op,free,1718,1)
    END_TYPE

    DEF_TYPE(struct jbd2_stats_proc_session)
        DEF_FIELD(struct jbd2_stats_proc_session,journal,1749,1)
        DEF_FIELD(struct jbd2_stats_proc_session,stats,1750,0)
        DEF_FIELD(struct jbd2_stats_proc_session,start,1751,0)
        DEF_FIELD(struct jbd2_stats_proc_session,max,1752,0)
    END_TYPE

    DEF_TYPE(struct posix_acl_entry)
        DEF_FIELD(struct posix_acl_entry,e_tag,1777,1)
        DEF_FIELD(struct posix_acl_entry,e_perm,1778,0)
        DEF_FIELD(struct posix_acl_entry,e_id,1779,0)
    END_TYPE

    DEF_TYPE(struct posix_acl)
        DEF_FIELD(struct posix_acl,a_refcount,1780,1)
        DEF_FIELD(struct posix_acl,a_count,1781,0)
        DEF_FIELD(struct posix_acl,a_entries,1782,0)
    END_TYPE

    DEF_TYPE(struct __wait_queue)
        DEF_FIELD(struct __wait_queue,flags,1785,1)
        DEF_FIELD(struct __wait_queue,private_data,1786,0)
        DEF_FIELD(struct __wait_queue,func,1787,0)
        DEF_FIELD(struct __wait_queue,task_list,1788,0)
    END_TYPE

    DEF_TYPE(struct block_device)
        DEF_FIELD(struct block_device,bd_dev,1789,1)
        DEF_FIELD(struct block_device,bd_inode,1790,0)
        DEF_FIELD(struct block_device,bd_super,1791,0)
        DEF_FIELD(struct block_device,bd_openers,1792,0)
        DEF_FIELD(struct block_device,bd_mutex,1793,0)
        DEF_FIELD(struct block_device,bd_inodes,1794,0)
        DEF_FIELD(struct block_device,bd_holder,1795,0)
        DEF_FIELD(struct block_device,bd_holders,1796,0)
        DEF_FIELD(struct block_device,bd_holder_list,1797,0)
        DEF_FIELD(struct block_device,bd_contains,1798,0)
        DEF_FIELD(struct block_device,bd_block_size,1799,0)
        DEF_FIELD(struct block_device,bd_part,1800,0)
        DEF_FIELD(struct block_device,bd_part_count,1801,0)
        DEF_FIELD(struct block_device,bd_invalidated,1802,0)
        DEF_FIELD(struct block_device,bd_disk,1803,0)
        DEF_FIELD(struct block_device,bd_list,1804,0)
        DEF_FIELD(struct block_device,bd_private,1805,0)
        DEF_FIELD(struct block_device,bd_fsfreeze_count,1806,0)
        DEF_FIELD(struct block_device,bd_fsfreeze_mutex,1807,0)
    END_TYPE

    DEF_TYPE(struct load_weight)
        DEF_FIELD(struct load_weight,weight,1808,1)
        DEF_FIELD(struct load_weight,inv_weight,1809,0)
    END_TYPE

    DEF_TYPE(struct rb_node)
        DEF_FIELD(struct rb_node,rb_parent_color,1810,1)
        DEF_FIELD(struct rb_node,rb_right,1811,0)
        DEF_FIELD(struct rb_node,rb_left,1812,0)
    END_TYPE

    DEF_TYPE(struct sched_entity)
        DEF_FIELD(struct sched_entity,load,1813,1)
        DEF_FIELD(struct sched_entity,run_node,1814,0)
        DEF_FIELD(struct sched_entity,group_node,1815,0)
        DEF_FIELD(struct sched_entity,on_rq,1816,0)
        DEF_FIELD(struct sched_entity,exec_start,1817,0)
        DEF_FIELD(struct sched_entity,sum_exec_runtime,1818,0)
        DEF_FIELD(struct sched_entity,vruntime,1819,0)
        DEF_FIELD(struct sched_entity,prev_sum_exec_runtime,1820,0)
        DEF_FIELD(struct sched_entity,last_wakeup,1821,0)
        DEF_FIELD(struct sched_entity,avg_overlap,1822,0)
        DEF_FIELD(struct sched_entity,nr_migrations,1823,0)
        DEF_FIELD(struct sched_entity,start_runtime,1824,0)
        DEF_FIELD(struct sched_entity,avg_wakeup,1825,0)
        DEF_FIELD(struct sched_entity,avg_running,1826,0)
        DEF_FIELD(struct sched_entity,wait_start,1827,0)
        DEF_FIELD(struct sched_entity,wait_max,1828,0)
        DEF_FIELD(struct sched_entity,wait_count,1829,0)
        DEF_FIELD(struct sched_entity,wait_sum,1830,0)
        DEF_FIELD(struct sched_entity,iowait_count,1831,0)
        DEF_FIELD(struct sched_entity,iowait_sum,1832,0)
        DEF_FIELD(struct sched_entity,sleep_start,1833,0)
        DEF_FIELD(struct sched_entity,sleep_max,1834,0)
        DEF_FIELD(struct sched_entity,sum_sleep_runtime,1835,0)
        DEF_FIELD(struct sched_entity,block_start,1836,0)
        DEF_FIELD(struct sched_entity,block_max,1837,0)
        DEF_FIELD(struct sched_entity,exec_max,1838,0)
        DEF_FIELD(struct sched_entity,slice_max,1839,0)
        DEF_FIELD(struct sched_entity,nr_migrations_cold,1840,0)
        DEF_FIELD(struct sched_entity,nr_failed_migrations_affine,1841,0)
        DEF_FIELD(struct sched_entity,nr_failed_migrations_running,1842,0)
        DEF_FIELD(struct sched_entity,nr_failed_migrations_hot,1843,0)
        DEF_FIELD(struct sched_entity,nr_forced_migrations,1844,0)
        DEF_FIELD(struct sched_entity,nr_forced2_migrations,1845,0)
        DEF_FIELD(struct sched_entity,nr_wakeups,1846,0)
        DEF_FIELD(struct sched_entity,nr_wakeups_sync,1847,0)
        DEF_FIELD(struct sched_entity,nr_wakeups_migrate,1848,0)
        DEF_FIELD(struct sched_entity,nr_wakeups_local,1849,0)
        DEF_FIELD(struct sched_entity,nr_wakeups_remote,1850,0)
        DEF_FIELD(struct sched_entity,nr_wakeups_affine,1851,0)
        DEF_FIELD(struct sched_entity,nr_wakeups_affine_attempts,1852,0)
        DEF_FIELD(struct sched_entity,nr_wakeups_passive,1853,0)
        DEF_FIELD(struct sched_entity,nr_wakeups_idle,1854,0)
        DEF_FIELD(struct sched_entity,parent,1855,0)
        DEF_FIELD(struct sched_entity,cfs_rq,1856,0)
        DEF_FIELD(struct sched_entity,my_q,1857,0)
    END_TYPE

    DEF_TYPE(struct sched_rt_entity)
        DEF_FIELD(struct sched_rt_entity,run_list,1858,1)
        DEF_FIELD(struct sched_rt_entity,timeout,1859,0)
        DEF_FIELD(struct sched_rt_entity,time_slice,1860,0)
        DEF_FIELD(struct sched_rt_entity,nr_cpus_allowed,1861,0)
        DEF_FIELD(struct sched_rt_entity,back,1862,0)
        DEF_FIELD(struct sched_rt_entity,parent,1863,0)
        DEF_FIELD(struct sched_rt_entity,rt_rq,1864,0)
        DEF_FIELD(struct sched_rt_entity,my_q,1865,0)
    END_TYPE

    DEF_TYPE(struct latency_record)
        DEF_FIELD(struct latency_record,backtrace,1866,1)
        DEF_FIELD(struct latency_record,count,1867,0)
        DEF_FIELD(struct latency_record,time,1868,0)
        DEF_FIELD(struct latency_record,max,1869,0)
    END_TYPE

    DEF_TYPE(struct cpumask)
        DEF_FIELD(struct cpumask,bits,1870,1)
    END_TYPE

    DEF_TYPE(struct prop_local_single)
        DEF_FIELD(struct prop_local_single,events,1871,1)
        DEF_FIELD(struct prop_local_single,period,1872,0)
        DEF_FIELD(struct prop_local_single,shift,1873,0)
        DEF_FIELD(struct prop_local_single,lock,1874,0)
    END_TYPE

    DEF_TYPE(nodemask_t)
        DEF_FIELD(nodemask_t,bits,1875,1)
    END_TYPE

    DEF_TYPE(union sigval)
        DEF_FIELD(union sigval,sival_int,1877,1)
        DEF_FIELD(union sigval,sival_ptr,1878,0)
    END_TYPE

    DEF_TYPE(struct siginfo)
        DEF_FIELD(struct siginfo,si_signo,1880,1)
        DEF_FIELD(struct siginfo,si_errno,1881,0)
        DEF_FIELD(struct siginfo,si_code,1882,0)
        DEF_FIELD(struct siginfo,_sifields,1906,0)
    END_TYPE

    DEF_TYPE(struct task_io_accounting)
        DEF_FIELD(struct task_io_accounting,rchar,1907,1)
        DEF_FIELD(struct task_io_accounting,wchar,1908,0)
        DEF_FIELD(struct task_io_accounting,syscr,1909,0)
        DEF_FIELD(struct task_io_accounting,syscw,1910,0)
        DEF_FIELD(struct task_io_accounting,read_bytes,1911,0)
        DEF_FIELD(struct task_io_accounting,write_bytes,1912,0)
        DEF_FIELD(struct task_io_accounting,cancelled_write_bytes,1913,0)
    END_TYPE

    DEF_TYPE(struct plist_head)
        DEF_FIELD(struct plist_head,prio_list,1914,1)
        DEF_FIELD(struct plist_head,node_list,1915,0)
    END_TYPE

    DEF_TYPE(seccomp_t)
        DEF_FIELD(seccomp_t,mode,1916,1)
    END_TYPE

    DEF_TYPE(struct sigpending)
        DEF_FIELD(struct sigpending,list,1917,1)
        DEF_FIELD(struct sigpending,signal,1918,0)
    END_TYPE

    DEF_TYPE(struct desc_struct)
        DEF_FIELD(struct desc_struct,a,1919,1)
        DEF_FIELD(struct desc_struct,b,1920,0)
        DEF_FIELD(struct desc_struct,limit0,1921,0)
        DEF_FIELD(struct desc_struct,base0,1922,0)
        DEF_FIELD(struct desc_struct,base1,1923,0)
        DEF_FIELD(struct desc_struct,type,1924,0)
        DEF_FIELD(struct desc_struct,s,1925,0)
        DEF_FIELD(struct desc_struct,dpl,1926,0)
        DEF_FIELD(struct desc_struct,p,1927,0)
        DEF_FIELD(struct desc_struct,limit,1928,0)
        DEF_FIELD(struct desc_struct,avl,1929,0)
        DEF_FIELD(struct desc_struct,l,1930,0)
        DEF_FIELD(struct desc_struct,d,1931,0)
        DEF_FIELD(struct desc_struct,g,1932,0)
        DEF_FIELD(struct desc_struct,base2,1933,0)
    END_TYPE

    DEF_TYPE(struct thread_struct)
        DEF_FIELD(struct thread_struct,tls_array,1934,1)
        DEF_FIELD(struct thread_struct,sp0,1935,0)
        DEF_FIELD(struct thread_struct,sp,1936,0)
        DEF_FIELD(struct thread_struct,usersp,1937,0)
        DEF_FIELD(struct thread_struct,es,1938,0)
        DEF_FIELD(struct thread_struct,ds,1939,0)
        DEF_FIELD(struct thread_struct,fsindex,1940,0)
        DEF_FIELD(struct thread_struct,gsindex,1941,0)
        DEF_FIELD(struct thread_struct,fs,1942,0)
        DEF_FIELD(struct thread_struct,gs,1943,0)
        DEF_FIELD(struct thread_struct,debugreg0,1944,0)
        DEF_FIELD(struct thread_struct,debugreg1,1945,0)
        DEF_FIELD(struct thread_struct,debugreg2,1946,0)
        DEF_FIELD(struct thread_struct,debugreg3,1947,0)
        DEF_FIELD(struct thread_struct,debugreg6,1948,0)
        DEF_FIELD(struct thread_struct,debugreg7,1949,0)
        DEF_FIELD(struct thread_struct,cr2,1950,0)
        DEF_FIELD(struct thread_struct,trap_no,1951,0)
        DEF_FIELD(struct thread_struct,error_code,1952,0)
        DEF_FIELD(struct thread_struct,xstate,1953,0)
        DEF_FIELD(struct thread_struct,io_bitmap_ptr,1954,0)
        DEF_FIELD(struct thread_struct,iopl,1955,0)
        DEF_FIELD(struct thread_struct,io_bitmap_max,1956,0)
        DEF_FIELD(struct thread_struct,debugctlmsr,1957,0)
        DEF_FIELD(struct thread_struct,ds_ctx,1958,0)
    END_TYPE

    DEF_TYPE(struct sched_info)
        DEF_FIELD(struct sched_info,pcount,1959,1)
        DEF_FIELD(struct sched_info,run_delay,1960,0)
        DEF_FIELD(struct sched_info,last_arrival,1961,0)
        DEF_FIELD(struct sched_info,last_queued,1962,0)
        DEF_FIELD(struct sched_info,bkl_count,1963,0)
    END_TYPE

    DEF_TYPE(struct sysv_sem)
        DEF_FIELD(struct sysv_sem,undo_list,1964,1)
    END_TYPE

    DEF_TYPE(struct plist_node)
        DEF_FIELD(struct plist_node,prio,1965,1)
        DEF_FIELD(struct plist_node,plist,1966,0)
    END_TYPE

    DEF_TYPE(struct pid_link)
        DEF_FIELD(struct pid_link,node,1967,1)
        DEF_FIELD(struct pid_link,pid,1968,0)
    END_TYPE

    DEF_TYPE(struct task_cputime)
        DEF_FIELD(struct task_cputime,utime,1969,1)
        DEF_FIELD(struct task_cputime,stime,1970,0)
        DEF_FIELD(struct task_cputime,sum_exec_runtime,1971,0)
    END_TYPE

    DEF_TYPE(struct task_struct)
        DEF_FIELD(struct task_struct,state,1972,1)
        DEF_FIELD(struct task_struct,stack,1973,0)
        DEF_FIELD(struct task_struct,usage,1974,0)
        DEF_FIELD(struct task_struct,flags,1975,0)
        DEF_FIELD(struct task_struct,ptrace,1976,0)
        DEF_FIELD(struct task_struct,lock_depth,1977,0)
        DEF_FIELD(struct task_struct,prio,1978,0)
        DEF_FIELD(struct task_struct,static_prio,1979,0)
        DEF_FIELD(struct task_struct,normal_prio,1980,0)
        DEF_FIELD(struct task_struct,rt_priority,1981,0)
        DEF_FIELD(struct task_struct,sched_class,1982,0)
        DEF_FIELD(struct task_struct,se,1983,0)
        DEF_FIELD(struct task_struct,rt,1984,0)
        DEF_FIELD(struct task_struct,preempt_notifiers,1985,0)
        DEF_FIELD(struct task_struct,fpu_counter,1986,0)
        DEF_FIELD(struct task_struct,btrace_seq,1987,0)
        DEF_FIELD(struct task_struct,policy,1988,0)
        DEF_FIELD(struct task_struct,cpus_allowed,1989,0)
        DEF_FIELD(struct task_struct,sched_info,1990,0)
        DEF_FIELD(struct task_struct,tasks,1991,0)
        DEF_FIELD(struct task_struct,pushable_tasks,1992,0)
        DEF_FIELD(struct task_struct,mm,1993,0)
        DEF_FIELD(struct task_struct,active_mm,1994,0)
        DEF_FIELD(struct task_struct,exit_state,1995,0)
        DEF_FIELD(struct task_struct,exit_code,1996,0)
        DEF_FIELD(struct task_struct,exit_signal,1997,0)
        DEF_FIELD(struct task_struct,pdeath_signal,1998,0)
        DEF_FIELD(struct task_struct,personality,1999,0)
        DEF_FIELD(struct task_struct,did_exec,2000,0)
        DEF_FIELD(struct task_struct,in_execve,2001,0)
        DEF_FIELD(struct task_struct,in_iowait,2002,0)
        DEF_FIELD(struct task_struct,sched_reset_on_fork,2003,0)
        DEF_FIELD(struct task_struct,pid,2004,0)
        DEF_FIELD(struct task_struct,tgid,2005,0)
        DEF_FIELD(struct task_struct,stack_canary,2006,0)
        DEF_FIELD(struct task_struct,real_parent,2007,0)
        DEF_FIELD(struct task_struct,parent,2008,0)
        DEF_FIELD(struct task_struct,children,2009,0)
        DEF_FIELD(struct task_struct,sibling,2010,0)
        DEF_FIELD(struct task_struct,group_leader,2011,0)
        DEF_FIELD(struct task_struct,ptraced,2012,0)
        DEF_FIELD(struct task_struct,ptrace_entry,2013,0)
        DEF_FIELD(struct task_struct,bts,2014,0)
        DEF_FIELD(struct task_struct,pids,2015,0)
        DEF_FIELD(struct task_struct,thread_group,2016,0)
        DEF_FIELD(struct task_struct,vfork_done,2017,0)
        DEF_FIELD(struct task_struct,set_child_tid,2018,0)
        DEF_FIELD(struct task_struct,clear_child_tid,2019,0)
        DEF_FIELD(struct task_struct,utime,2020,0)
        DEF_FIELD(struct task_struct,stime,2021,0)
        DEF_FIELD(struct task_struct,utimescaled,2022,0)
        DEF_FIELD(struct task_struct,stimescaled,2023,0)
        DEF_FIELD(struct task_struct,gtime,2024,0)
        DEF_FIELD(struct task_struct,prev_utime,2025,0)
        DEF_FIELD(struct task_struct,prev_stime,2026,0)
        DEF_FIELD(struct task_struct,nvcsw,2027,0)
        DEF_FIELD(struct task_struct,nivcsw,2028,0)
        DEF_FIELD(struct task_struct,start_time,2029,0)
        DEF_FIELD(struct task_struct,real_start_time,2030,0)
        DEF_FIELD(struct task_struct,min_flt,2031,0)
        DEF_FIELD(struct task_struct,maj_flt,2032,0)
        DEF_FIELD(struct task_struct,cputime_expires,2033,0)
        DEF_FIELD(struct task_struct,cpu_timers,2034,0)
        DEF_FIELD(struct task_struct,real_cred,2035,0)
        DEF_FIELD(struct task_struct,cred,2036,0)
        DEF_FIELD(struct task_struct,cred_guard_mutex,2037,0)
        DEF_FIELD(struct task_struct,replacement_session_keyring,2038,0)
        DEF_FIELD(struct task_struct,comm,2039,0)
        DEF_FIELD(struct task_struct,link_count,2040,0)
        DEF_FIELD(struct task_struct,total_link_count,2041,0)
        DEF_FIELD(struct task_struct,sysvsem,2042,0)
        DEF_FIELD(struct task_struct,last_switch_count,2043,0)
        DEF_FIELD(struct task_struct,thread,2044,0)
        DEF_FIELD(struct task_struct,fs,2045,0)
        DEF_FIELD(struct task_struct,files,2046,0)
        DEF_FIELD(struct task_struct,nsproxy,2047,0)
        DEF_FIELD(struct task_struct,signal,2048,0)
        DEF_FIELD(struct task_struct,sighand,2049,0)
        DEF_FIELD(struct task_struct,blocked,2050,0)
        DEF_FIELD(struct task_struct,real_blocked,2051,0)
        DEF_FIELD(struct task_struct,saved_sigmask,2052,0)
        DEF_FIELD(struct task_struct,pending,2053,0)
        DEF_FIELD(struct task_struct,sas_ss_sp,2054,0)
        DEF_FIELD(struct task_struct,sas_ss_size,2055,0)
        DEF_FIELD(struct task_struct,notifier,2056,0)
        DEF_FIELD(struct task_struct,notifier_data,2057,0)
        DEF_FIELD(struct task_struct,notifier_mask,2058,0)
        DEF_FIELD(struct task_struct,audit_context,2059,0)
        DEF_FIELD(struct task_struct,loginuid,2060,0)
        DEF_FIELD(struct task_struct,sessionid,2061,0)
        DEF_FIELD(struct task_struct,seccomp,2062,0)
        DEF_FIELD(struct task_struct,parent_exec_id,2063,0)
        DEF_FIELD(struct task_struct,self_exec_id,2064,0)
        DEF_FIELD(struct task_struct,alloc_lock,2065,0)
        DEF_FIELD(struct task_struct,irqaction,2066,0)
        DEF_FIELD(struct task_struct,pi_lock,2067,0)
        DEF_FIELD(struct task_struct,pi_waiters,2068,0)
        DEF_FIELD(struct task_struct,pi_blocked_on,2069,0)
        DEF_FIELD(struct task_struct,journal_info,2070,0)
        DEF_FIELD(struct task_struct,bio_list,2071,0)
        DEF_FIELD(struct task_struct,bio_tail,2072,0)
        DEF_FIELD(struct task_struct,reclaim_state,2073,0)
        DEF_FIELD(struct task_struct,backing_dev_info,2074,0)
        DEF_FIELD(struct task_struct,io_context,2075,0)
        DEF_FIELD(struct task_struct,ptrace_message,2076,0)
        DEF_FIELD(struct task_struct,last_siginfo,2077,0)
        DEF_FIELD(struct task_struct,ioac,2078,0)
        DEF_FIELD(struct task_struct,acct_rss_mem1,2079,0)
        DEF_FIELD(struct task_struct,acct_vm_mem1,2080,0)
        DEF_FIELD(struct task_struct,acct_timexpd,2081,0)
        DEF_FIELD(struct task_struct,mems_allowed,2082,0)
        DEF_FIELD(struct task_struct,cpuset_mem_spread_rotor,2083,0)
        DEF_FIELD(struct task_struct,cgroups,2084,0)
        DEF_FIELD(struct task_struct,cg_list,2085,0)
        DEF_FIELD(struct task_struct,robust_list,2086,0)
        DEF_FIELD(struct task_struct,compat_robust_list,2087,0)
        DEF_FIELD(struct task_struct,pi_state_list,2088,0)
        DEF_FIELD(struct task_struct,pi_state_cache,2089,0)
        DEF_FIELD(struct task_struct,perf_event_ctxp,2090,0)
        DEF_FIELD(struct task_struct,perf_event_mutex,2091,0)
        DEF_FIELD(struct task_struct,perf_event_list,2092,0)
        DEF_FIELD(struct task_struct,mempolicy,2093,0)
        DEF_FIELD(struct task_struct,il_next,2094,0)
        DEF_FIELD(struct task_struct,fs_excl,2095,0)
        DEF_FIELD(struct task_struct,rcu,2096,0)
        DEF_FIELD(struct task_struct,splice_pipe,2097,0)
        DEF_FIELD(struct task_struct,dirties,2098,0)
        DEF_FIELD(struct task_struct,latency_record_count,2099,0)
        DEF_FIELD(struct task_struct,latency_record,2100,0)
        DEF_FIELD(struct task_struct,timer_slack_ns,2101,0)
        DEF_FIELD(struct task_struct,default_timer_slack_ns,2102,0)
        DEF_FIELD(struct task_struct,scm_work_list,2103,0)
        DEF_FIELD(struct task_struct,curr_ret_stack,2104,0)
        DEF_FIELD(struct task_struct,ret_stack,2105,0)
        DEF_FIELD(struct task_struct,ftrace_timestamp,2106,0)
        DEF_FIELD(struct task_struct,trace_overrun,2107,0)
        DEF_FIELD(struct task_struct,tracing_graph_pause,2108,0)
        DEF_FIELD(struct task_struct,trace,2109,0)
        DEF_FIELD(struct task_struct,trace_recursion,2110,0)
    END_TYPE

    DEF_TYPE(struct kthread_create_info)
        DEF_FIELD(struct kthread_create_info,threadfn,2111,1)
        DEF_FIELD(struct kthread_create_info,data,2112,0)
        DEF_FIELD(struct kthread_create_info,result,2113,0)
        DEF_FIELD(struct kthread_create_info,done,2114,0)
        DEF_FIELD(struct kthread_create_info,list,2115,0)
    END_TYPE

    DEF_TYPE(struct journal_head)
        DEF_FIELD(struct journal_head,b_bh,2119,1)
        DEF_FIELD(struct journal_head,b_jcount,2120,0)
        DEF_FIELD(struct journal_head,b_jlist,2121,0)
        DEF_FIELD(struct journal_head,b_modified,2122,0)
        DEF_FIELD(struct journal_head,b_frozen_data,2123,0)
        DEF_FIELD(struct journal_head,b_committed_data,2124,0)
        DEF_FIELD(struct journal_head,b_transaction,2125,0)
        DEF_FIELD(struct journal_head,b_next_transaction,2126,0)
        DEF_FIELD(struct journal_head,b_tnext,2127,0)
        DEF_FIELD(struct journal_head,b_tprev,2128,0)
        DEF_FIELD(struct journal_head,b_cp_transaction,2129,0)
        DEF_FIELD(struct journal_head,b_cpnext,2130,0)
        DEF_FIELD(struct journal_head,b_cpprev,2131,0)
        DEF_FIELD(struct journal_head,b_triggers,2132,0)
        DEF_FIELD(struct journal_head,b_frozen_triggers,2133,0)
    END_TYPE

    DEF_TYPE(struct generic_type)
        DEF_FIELD(struct generic_type,type,2134,1)
        DEF_FIELD(struct generic_type,mode,2135,0)
    END_TYPE

    DEF_TYPE(struct generic_bl_info)
        DEF_FIELD(struct generic_bl_info,name,2137,1)
        DEF_FIELD(struct generic_bl_info,max_intensity,2138,0)
        DEF_FIELD(struct generic_bl_info,default_intensity,2139,0)
        DEF_FIELD(struct generic_bl_info,limit_mask,2140,0)
        DEF_FIELD(struct generic_bl_info,set_bl_intensity,2141,0)
        DEF_FIELD(struct generic_bl_info,kick_battery,2142,0)
    END_TYPE

    DEF_TYPE(struct match_token)
        DEF_FIELD(struct match_token,token,2144,1)
        DEF_FIELD(struct match_token,pattern,2145,0)
    END_TYPE


END_MOP

