cmd_/home/akshayk/GranaryCode/Granary-Drk/src/core/kernel_linux/modules/../../kernel_linux/clients/cfi/cfi_atomic.o := gcc -Wp,-MD,/home/akshayk/GranaryCode/Granary-Drk/src/core/kernel_linux/modules/../../kernel_linux/clients/cfi/.cfi_atomic.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/4.7/include -I/home/akshayk/GranaryCode/Granary-Drk/src/debugging/linux-3.2.33/arch/x86/include -Iarch/x86/include/generated -Iinclude  -include /home/akshayk/GranaryCode/Granary-Drk/src/debugging/linux-3.2.33/include/linux/kconfig.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -O2 -m64 -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -fstack-protector -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -Wframe-larger-than=1024 -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -g -pg -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -O3 -g -DDR_REG_ENUM_COMPATIBILITY -DX86_64 -DLINUX -DLINUX_KERNEL -I/home/akshayk/GranaryCode/Granary-Drk/src/core/lib/include -I/home/akshayk/GranaryCode/Granary-Drk/src/core/kernel_linux -I/home/akshayk/GranaryCode/Granary-Drk/src/core/lib -I/home/akshayk/GranaryCode/Granary-Drk/src/core/x86 -I/home/akshayk/GranaryCode/Granary-Drk/src/core -Wframe-larger-than=4096  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(cfi_atomic)"  -D"KBUILD_MODNAME=KBUILD_STR(cfi)" -c -o /home/akshayk/GranaryCode/Granary-Drk/src/core/kernel_linux/modules/../../kernel_linux/clients/cfi/.tmp_cfi_atomic.o /home/akshayk/GranaryCode/Granary-Drk/src/core/kernel_linux/modules/../../kernel_linux/clients/cfi/cfi_atomic.c

source_/home/akshayk/GranaryCode/Granary-Drk/src/core/kernel_linux/modules/../../kernel_linux/clients/cfi/cfi_atomic.o := /home/akshayk/GranaryCode/Granary-Drk/src/core/kernel_linux/modules/../../kernel_linux/clients/cfi/cfi_atomic.c

deps_/home/akshayk/GranaryCode/Granary-Drk/src/core/kernel_linux/modules/../../kernel_linux/clients/cfi/cfi_atomic.o := \
  /home/akshayk/GranaryCode/Granary-Drk/src/core/kernel_linux/modules/../../kernel_linux/clients/cfi/cfi_atomic.h \

/home/akshayk/GranaryCode/Granary-Drk/src/core/kernel_linux/modules/../../kernel_linux/clients/cfi/cfi_atomic.o: $(deps_/home/akshayk/GranaryCode/Granary-Drk/src/core/kernel_linux/modules/../../kernel_linux/clients/cfi/cfi_atomic.o)

$(deps_/home/akshayk/GranaryCode/Granary-Drk/src/core/kernel_linux/modules/../../kernel_linux/clients/cfi/cfi_atomic.o):
